from enum import Enum


class ActiviteitMetrics(str, Enum):
    ACTIVITEIT_ID = "ActiviteitId"
    NUMMER = "Nummer"
    MINISTERIE = "MinisterieNaam"
    MINISTERIE_AFKORTING = "Ministerie"
    ORGANISATIE = "OrganisatieNaam"
    NAAM = "Naam"
    ONDERWERP = "Onderwerp"
    DIENSTVERLENING = "Dienstverlening"
    SOORT = "SoortICTActiviteit"
    BAAT = "MaatschappelijkeBaat"
    STARTDATUM = "StartDatum"
    ONTWIKKELWIJZE = "Ontwikkelwijze"
    SCHATTING_EINDDATUM_INITIEEL = "SchattingEinddatumInitieel"
    SCHATTING_EINDDATUM_ACTUEEL = "SchattingEinddatumActueel"
    SCHATTING_TOTALE_KOSTEN_INITIEEL = "SchattingTotaleKostenInitieel"
    SCHATTING_TOTALE_KOSTEN_HUIDIG_JAAR = "SchattingTotaleKostenHuidigJaar"
    SCHATTING_TOTALE_KOSTEN_VORIG_JAAR = "SchattingTotaleKostenVorigJaar"
    DAADWERKELIJK_OVERIGE_KOSTEN = "OverigeKostenDaadwerkelijk"
    DAADWERKELIJK_INTERN_PERSONEEL = "InternPersoneelDaadwerkelijk"
    DAADWERKELIJK_EXTERN_PERSONEEL = "ExternPersoneelDaadwerkelijk"
    DAADWERKELIJK_UITBESTEED_WERK = "UitbesteedWerkDaadwerkelijk"
    DAADWERKELIJK_INBESTEED_WERK = "InbesteedWerkDaadwerkelijk"
    DAADWERKELIJK_DATAVERBINDINGEN = "DataverbindingenDaadwerkelijk"
    DAADWERKELIJK_STANDAARDSOFTWARE = "StandaardsoftwareDaadwerkelijk"
    DAADWERKELIJK_HARDWARE = "HardwareDaadwerkelijk"
    DAADWERKELIJK_HARDWARE_SOFTWARE = "HardwareSoftwareDaadwerkelijk"
    DAADWERKELIJK_OVERIG_MATERIEEL = "OverigMaterieelDaadwerkelijk"

    ACTUEEL_OVERIGE_KOSTEN = "OverigeKostenActueel"
    ACTUEEL_INTERN_PERSONEEL = "InternPersoneelActueel"
    ACTUEEL_EXTERN_PERSONEEL = "ExternPersoneelActueel"
    ACTUEEL_UITBESTEED_WERK = "UitbesteedWerkActueel"
    ACTUEEL_INBESTEED_WERK = "InbesteedWerkActueel"
    ACTUEEL_DATAVERBINDINGEN = "DataverbindingenActueel"
    ACTUEEL_STANDAARDSOFTWARE = "StandaardsoftwareActueel"
    ACTUEEL_HARDWARE = "HardwareActueel"
    ACTUEEL_HARDWARE_SOFTWARE = "HardwareSoftwareActueel"
    ACTUEEL_OVERIG_MATERIEEL = "OverigMaterieelActueel"

    INITIEEL_OVERIGE_KOSTEN = "OverigeKostenInitieel"
    INITIEEL_INTERN_PERSONEEL = "InternPersoneelInitieel"
    INITIEEL_EXTERN_PERSONEEL = "ExternPersoneelInitieel"
    INITIEEL_UITBESTEED_WERK = "UitbesteedWerkInitieel"
    INITIEEL_INBESTEED_WERK = "InbesteedWerkInitieel"
    INITIEEL_DATAVERBINDINGEN = "DataverbindingenInitieel"
    INITIEEL_STANDAARDSOFTWARE = "StandaardsoftwareInitieel"
    INITIEEL_HARDWARE = "HardwareInitieel"
    INITIEEL_HARDWARE_SOFTWARE = "HardwareSoftwareInitieel"
    INITIEEL_OVERIG_MATERIEEL = "OverigMaterieelInitieel"

    CUMULATIEVEKOSTEN_HUIDIG_JAAR = "CumulatieveKostenHuidigJaar"
    CUMULATIEVE_KOSTEN_VORIG_JAAR = "CumulatieveKostenVorigJaar"
    PROGNOSE_TOEKOMSTIGE_KOSTEN = "PrognoseToekomstigeKosten"
    ACTIEF_IN_JBR_JAAR = "ActiefInJbrJaar"
    STATUS = "ProjectStatus"
    VERSCHIL_EINDDATUM_INITIEEL_ACTUEEL_IN_JAREN = (
        "VerschilEindatumInitieelActueelInJaren"
    )
    EINDDATUM_EERDER_LATER = "Eindatum eerder/later"
    DOORLOOPTIJD_ACTUEEL = "DoorlooptijdActueel"
    DOORLOOPTIJD_INITIEEL = "DoorlooptijdInitieel"
    VERSCHIL_DOORLOOPTIJD_PCT = "VerschilDoorlooptijdPct"
    DOORLOOPTIJD_EERDER_LATER_PCT = "DoorlooptijdEerderLaterPct"
    TOTALE_KOSTEN_CATEGORIE = "TotaleKostenCategorie"
    REDENEN_HERIJKINGEN = "RedenenHerijkingen"
    ONTWIKKELPARTIJEN = "Ontwikkelpartijen"
    AANTAL_BATEN = "AantalBaten"
    AANTAL_BEHAALDE_MIJLPALEN = "AantalBehaaldeMijlpalen"
    AANTAL_ACICT_ADVIEZEN = "AantalAcICTAdviezen"
    HEEFT_ACICT_ADVIES = "HeeftAcICTAdvies"
    STARTJAAR = "StartJaar"
    EINDJAAR = "EindJaar"
