services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./dev_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rid-data

  dbgate:
    image: dbgate/dbgate:alpine
    volumes:
      - dbgate:/root/.dbgate
    depends_on:
      - db
    ports:
      - 8091:3000
    environment:
      # docs: https://dbgate.org/docs/env-variables.html
      CONNECTIONS: 'CON1'
      LABEL_CON1: 'Postgres'
      SERVER_CON1: 'db'
      USER_CON1: ${POSTGRES_USER}
      PASSWORD_CON1: ${POSTGRES_PASSWORD}
      PORT_CON1: 5432
      ENGINE_CON1: postgres@dbgate-plugin-postgres
      # SINGLE_CONNECTION: 'CON1'
      # SINGLE_DATABASE: ${POSTGRES_DB}

volumes:
  dbgate:
  postgres:
