import json

from pydantic import BaseModel

excel_column_mapping = {
    "MinisterieNaam": "Ministerie (naam)",
    "ProjectStatus": "Status",
    "Naam": "ICT-activiteit",
    "SoortICTActiviteit": "Soort ICT-activiteit",
    "MaatschappelijkeBaat": "Wij verbeteren op",
    "AantalBaten": "Aantal baten",
    "AantalBehaaldeMijlpalen": "Aantal behaalde mijlpalen",
    "HeeftAcICTAdvies": "AcICT-advies",
    "AantalAcICTAdviezen": "Aantal AcICT-adviezen",
    "StartDatum": "Startdatum",
    "SchattingEinddatumInitieel": "Initiële schatting einddatum",
    "SchattingEinddatumActueel": "Actuele schatting einddatum",
    "StartJaar": "Startjaar",
    "EindJaar": "Actueel eindjaar",
    "DoorlooptijdInitieel": "Doorlooptijd initieel",
    "DoorlooptijdActueel": "Actuele doorlooptijd",
    "VerschilEindatumInitieelActueelInJaren": "Verschil initieel en actueel (in jaren)",
    "VerschilDoorlooptijdPct": "Verschil doorlooptijd (percentage)",
    "Eindatum eerder/later": "Aanpassing einddatum (absoluut)",
    "DoorlooptijdEerderLaterPct": "Aanpassing einddatum (relatief)",
    "RedenenHerijkingen": "Reden herijking",
    "SchattingTotaleKostenInitieel": "Initiële schatting meerjarige kosten",
    "SchattingTotaleKostenHuidigJaar": "Actuele schatting meerjarige kosten huidige jaar",
    "TotaleKostenCategorie": "Actuele kostencategorie",
    "SchattingTotaleKostenVorigJaar": "Actuele schatting meerjarige kosten vorig jaar",
    "PrognoseToekomstigeKosten": "Prognose toekomstige kosten",
    "CumulatieveKostenHuidigJaar": "Cumulatieve meerjarige uitgaven t/m huidige jaar",
    "CumulatieveKostenVorigJaar": "Cumulatieve meerjarige uitgaven t/m vorig jaar",
    "InternPersoneelInitieel": "Schatting initiële kosten intern personeel",
    "ExternPersoneelInitieel": "Schatting initiële kosten extern personeel",
    "OverigMaterieelInitieel": "Schatting initiële kosten overig materieel",
    "HardwareSoftwareInitieel": "Schatting initiële kosten Software, hardware en dataverbindingen (oud)",
    "HardwareInitieel": "Schatting initiële kosten hardware (oud)",
    "StandaardsoftwareInitieel": "Schatting initiële kosten standaard software (oud)",
    "DataverbindingenInitieel": "Schatting initiële kosten dataverbindingen (oud)",
    "UitbesteedWerkInitieel": "Schatting initiële kostenuitbesteed werk",
    "InbesteedWerkInitieel": "Schatting initiële kosteninbesteed werk (oud)",
    "OverigeKostenInitieel": "Schatting initiële kostenoverig (oud)",
    "InternPersoneelActueel": "Schatting actuele kosten intern personeel",
    "ExternPersoneelActueel": "Schatting actuele kosten extern personeel",
    "OverigMaterieelActueel": "Schatting actuele kosten overig materieel",
    "HardwareSoftwareActueel": "Schatting actuele kosten Software, hardware en dataverbindingen (oud)",
    "HardwareActueel": "Schatting actuele kosten hardware (oud)",
    "StandaardsoftwareActueel": "Schatting actuele kosten standaard software (oud)",
    "DataverbindingenActueel": "Schatting actuele kosten dataverbindingen (oud)",
    "UitbesteedWerkActueel": "Schatting actuele kosten uitbesteed werk",
    "InbesteedWerkActueel": "Schatting actuele kosten inbesteed werk (oud)",
    "OverigeKostenActueel": "Schatting actuele kosten overig (oud)",
    "InternPersoneelDaadwerkelijk": "Daadwerkelijke uitgaven intern personeel",
    "ExternPersoneelDaadwerkelijk": "Daadwerkelijke uitgaven extern personeel",
    "OverigMaterieelDaadwerkelijk": "Daadwerkelijke uitgaven overig materieel",
    "HardwareSoftwareDaadwerkelijk": "Daadwerkelijke uitgaven Software, hardware en dataverbindingen (oud)",
    "HardwareDaadwerkelijk": "Daadwerkelijke uitgaven hardware (oud)",
    "StandaardsoftwareDaadwerkelijk": "Daadwerkelijke uitgaven standaard software (oud)",
    "DataverbindingenDaadwerkelijk": "Daadwerkelijke uitgaven dataverbindingen (oud)",
    "UitbesteedWerkDaadwerkelijk": "Daadwerkelijke uitgaven uitbesteed werk",
    "InbesteedWerkDaadwerkelijk": "Daadwerkelijke uitgaven inbesteed werk (oud)",
    "OverigeKostenDaadwerkelijk": "Daadwerkelijke uitgaven overig (oud)",
}

column_order = [
    "Nummer",
    "Ministerie",
    "MinisterieNaam",
    "Naam",
    "ProjectStatus",
    "SoortICTActiviteit",
    "Onderwerp",
    "Dienstverlening",
    "MaatschappelijkeBaat",
    "AantalBaten",
    "AantalBehaaldeMijlpalen",
    "Ontwikkelpartijen",
    "Ontwikkelwijze",
    "HeeftAcICTAdvies",
    "AantalAcICTAdviezen",
    "StartDatum",
    "SchattingEinddatumInitieel",
    "SchattingEinddatumActueel",
    "StartJaar",
    "EindJaar",
    "DoorlooptijdInitieel",
    "DoorlooptijdActueel",
    "VerschilEindatumInitieelActueelInJaren",
    "VerschilDoorlooptijdPct",
    "Eindatum eerder/later",
    "DoorlooptijdEerderLaterPct",
    "RedenenHerijkingen",
    "SchattingTotaleKostenInitieel",
    "SchattingTotaleKostenHuidigJaar",
    "TotaleKostenCategorie",
    "SchattingTotaleKostenVorigJaar",
    "PrognoseToekomstigeKosten",
    "InternPersoneelInitieel",
    "ExternPersoneelInitieel",
    "OverigMaterieelInitieel",
    "HardwareSoftwareInitieel",
    "HardwareInitieel",
    "StandaardsoftwareInitieel",
    "DataverbindingenInitieel",
    "UitbesteedWerkInitieel",
    "InbesteedWerkInitieel",
    "OverigeKostenInitieel",
    "InternPersoneelActueel",
    "ExternPersoneelActueel",
    "OverigMaterieelActueel",
    "HardwareSoftwareActueel",
    "HardwareActueel",
    "StandaardsoftwareActueel",
    "DataverbindingenActueel",
    "UitbesteedWerkActueel",
    "InbesteedWerkActueel",
    "OverigeKostenActueel",
    "CumulatieveKostenHuidigJaar",
    "CumulatieveKostenVorigJaar",
    "InternPersoneelDaadwerkelijk",
    "ExternPersoneelDaadwerkelijk",
    "OverigMaterieelDaadwerkelijk",
    "HardwareSoftwareDaadwerkelijk",
    "HardwareDaadwerkelijk",
    "StandaardsoftwareDaadwerkelijk",
    "DataverbindingenDaadwerkelijk",
    "UitbesteedWerkDaadwerkelijk",
    "InbesteedWerkDaadwerkelijk",
    "OverigeKostenDaadwerkelijk",
]


class ExcelCell(BaseModel):
    body: str | None
    bold: bool


def get_excel_toelichting_cells() -> list[ExcelCell]:
    json_path = "app/assets/toelichting_excel.json"
    with open(json_path) as f:
        excel_toelichting_dict = json.load(f)
        return [ExcelCell(**cell) for cell in excel_toelichting_dict]
