"""AddLockBooleans to UpdateOrganisaties

Revsion ID: 54f8f9990fe9
Revises: 3fb8f290bbe5
Create Date: 2023-03-15 16:09:00

upgrade
script-migration AddLockBooleans UpdateOrganisaties
downgrade
script-migration UpdateOrganisaties AddLockBooleans

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "54f8f9990fe9"
down_revision = "3fb8f290bbe5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    upgrade_query = """

        START TRANSACTION;

        ALTER TABLE "Project" ADD "OrganisatieId" integer NULL;

        CREATE TABLE "Organisatie" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Naam" text NULL,
            "MinisterieId" integer NOT NULL,
            CONSTRAINT "PK_Organisatie" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Organisatie_Ministerie_MinisterieId" FOREIGN KEY ("MinisterieId") REFERENCES "Ministerie" ("Id") ON DELETE CASCADE
        );

        CREATE TABLE "GebruikerOrganisatie" (
            "GebruikersId" text NOT NULL,
            "OrganisatiesId" integer NOT NULL,
            CONSTRAINT "PK_GebruikerOrganisatie" PRIMARY KEY ("GebruikersId", "OrganisatiesId"),
            CONSTRAINT "FK_GebruikerOrganisatie_AspNetUsers_GebruikersId" FOREIGN KEY ("GebruikersId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_GebruikerOrganisatie_Organisatie_OrganisatiesId" FOREIGN KEY ("OrganisatiesId") REFERENCES "Organisatie" ("Id") ON DELETE CASCADE
        );

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '1ab9bbcb-db75-434c-9f5d-02c8bdee3b32', "SecurityStamp" = 'cb9d75ce-fb98-404d-affd-303b3bd7fc3f'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '274d5473-27cf-4e20-b6f3-c95c974dabe7', "SecurityStamp" = '05711243-e0ff-4354-9aad-76c8744d911d'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'dfdcc757-758f-4632-97f5-c9a7c36adbf1', "SecurityStamp" = '6745fe68-7ce5-4452-b3b2-4f5eeb649d8a'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '8e4e32b2-8d91-4316-97b5-44794474bb8c', "SecurityStamp" = 'f083c682-00fd-47eb-ba1d-53eb0052b8f8'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '26febe77-cb07-4a5a-be8e-bcafa0fa4788'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        CREATE INDEX "IX_Project_OrganisatieId" ON "Project" ("OrganisatieId");

        CREATE INDEX "IX_GebruikerOrganisatie_OrganisatiesId" ON "GebruikerOrganisatie" ("OrganisatiesId");

        CREATE INDEX "IX_Organisatie_MinisterieId" ON "Organisatie" ("MinisterieId");

        ALTER TABLE "Project" ADD CONSTRAINT "FK_Project_Organisatie_OrganisatieId" FOREIGN KEY ("OrganisatieId") REFERENCES "Organisatie" ("Id");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230306090830_AddOrganisatieTable', '6.0.13');

        COMMIT;

        START TRANSACTION;

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '2849eb9c-52bf-4d27-bdc7-649dd0028de1', "SecurityStamp" = '7cf202da-ea68-4ac2-8371-0cc79a828ded'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '7b612ec9-4bfa-4172-950f-086988476dd6', "SecurityStamp" = '11cdffdd-c767-4223-8ec3-2f5200eb2fc9'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '0a385235-fc3d-42f3-9309-0be93a861ba6', "SecurityStamp" = '5a7e558f-eae4-4275-acd5-f9286d378640'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'c52b3d39-6f52-42ea-bd7f-ad45d58dde30', "SecurityStamp" = 'afa86ff5-21b1-4978-a241-77c3a345dce6'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = 'c801496c-7b9a-42df-acb4-973ed0b8b693'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (1, 5, 'Agentschap Telecom');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (2, 6, 'Belastingdienst');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (3, 12, 'Centraal Administratie Kantoor (CAK)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (4, 7, 'Centraal Bureau Rijvaardigheidsbewijzen (CBR)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (5, 5, 'Centraal Bureau voor de Statistiek (CBS)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (6, 8, 'Centraal Justitieel Incassobureau (CJIB)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (7, 12, 'Centrum indicatiestelling zorg (CIZ)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (8, 5, 'Dienst ICT Uitvoering (DICTU)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (9, 8, 'Dienst Justitiële Inrichtingen');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (10, 8, 'Dienst Terugkeer en Vertrek');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (11, 10, 'Dienst Uitvoering Onderwijs (DUO)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (12, 12, 'Dienst Uitvoering Subsidies aan Instellingen (DUS-I)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (13, 7, 'Dienst Wegverkeer (RDW)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (14, 3, 'Directie Consulaire zaken en Visumbeleid (DCV)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (15, 6, 'Douane');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (16, 6, 'Generale Thesaurie');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (17, 8, 'Immigratie- en Naturalisatiedienst (IND)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (18, 12, 'Inspectie Gezondheidszorg en Jeugd (IGJ)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (19, 7, 'Inspectie Leefomgeving en Transport');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (20, 8, 'Justis');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (21, 2, 'Kadaster');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (22, 5, 'Kamer van Koophandel (KvK)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (23, 2, 'Kiesraad');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (24, 7, 'Koninklijk Nederlands Meteorologisch Instituut (KNMI)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (25, 10, 'Koninklijke Bibliotheek (KB)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (26, 4, 'Koninklijke Marechaussee');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (27, 4, 'Kustwacht');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (28, 2, 'Logius');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (29, 7, 'Luchtverkeersleiding Nederland (LVNL)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (30, 5, 'Nationaal Coördinator Groningen');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (31, 8, 'Nederlands Forensisch Instituut');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (32, 9, 'Nederlandse Voedsel-en Warenautoriteit (NVWA)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (33, 8, 'Openbaar Ministerie (OM)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (34, 2, 'Organisatie en Personeel Rijk (P-Direkt)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (35, 8, 'Raad voor de rechtspraak');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (36, 10, 'Rijksdienst voor het Cultureel Erfgoed');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (37, 2, 'Rijksdienst voor Identiteitsgegevens (RvIG)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (38, 5, 'Rijksdienst voor Ondernemend Nederland (RVO)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (39, 2, 'Rijksvastgoedbedrijf (RVB)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (40, 7, 'Rijkswaterstaat');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (41, 2, 'Shared Service Center ICT (SSC-ICT)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (42, 11, 'Sociale Verzekeringsbank (SVB)');
        INSERT INTO "Organisatie" ("Id", "MinisterieId", "Naam")
        VALUES (43, 11, 'Uitvoeringsinstituut Werknemersverzekeringen (UWV)');

        SELECT setval(
            pg_get_serial_sequence('"Organisatie"', 'Id'),
            GREATEST(
                (SELECT MAX("Id") FROM "Organisatie") + 1,
                nextval(pg_get_serial_sequence('"Organisatie"', 'Id'))),
            false);

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230313135455_SeedOrganisaties', '6.0.13');

        COMMIT;

        START TRANSACTION;

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '053486b3-c0b0-4dc9-8d1d-19ff023126ce', "SecurityStamp" = '2c8186fc-067a-4d68-8064-2d0b55de0b3a'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '4cc3ac38-6b73-4b02-9b3e-d49943fc32da', "SecurityStamp" = 'be76e90f-0c43-4fa1-bbc4-f09db7ae40c4'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '8d590628-f444-4bc1-bb9b-66090b3e80f6', "SecurityStamp" = '3bb871d9-48c2-496f-997e-a37f52d65cb4'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '2fc033d7-fa1e-4a63-b3ea-6b93de2dd53d', "SecurityStamp" = '68520366-cde8-4024-b5f3-2b3fe36dcf7d'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '298b654f-dd1c-49dc-9892-3673b1fd3f7c'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        UPDATE "public"."IndicatorLijst"
        SET "IsLockable"='true'
        WHERE ("public"."IndicatorLijst"."Id" = 'a424c56c-e3e0-451a-bd0c-4f1c2d2108f3')
        ;

        DELETE FROM "public"."AntwoordOptie"
        WHERE ("public"."AntwoordOptie"."Id" = 204)
        ;

        UPDATE "public"."Antwoord"
        SET "Waarde"='Familie, zorg en gezondheid'
        WHERE ("public"."Antwoord"."Id" = 58888)
        ;

        UPDATE "public"."AntwoordOptie"
        SET "Waarde"=' Geannuleerd'
        WHERE ("public"."AntwoordOptie"."Id" = 83)
        ;
        UPDATE "public"."AntwoordOptie"
        SET "Waarde"='  In heroriëntatie'
        WHERE ("public"."AntwoordOptie"."Id" = 84)
        ;
        UPDATE "public"."AntwoordOptie"
        SET "Waarde"='   In uitvoering'
        WHERE ("public"."AntwoordOptie"."Id" = 85)
        ;
        UPDATE "public"."AntwoordOptie"
        SET "Waarde"='    Nog niet gestart'
        WHERE ("public"."AntwoordOptie"."Id" = 653)
        ;

        UPDATE public."Project" SET "OrganisatieId" = neworganisatieid 
        FROM  
        (
        SELECT 
            projectnummer,
            max(neworganisatieid) as neworganisatieid,
            max(organisatieid) as organisatieid,
            max(projectnaam) as projectnaam
            FROM
            (
                SELECT pv_1."Id" AS "ProjectVersieId",
                    project."Naam" as  projectnaam,
                    project."Nummer" as projectnummer,
                    a."Waarde",
                    organisatie."Naam" as organisatienaam,
                    organisatie."Id" as organisatieid,
                    CASE 
                        WHEN a."Waarde" = 'Belastingdienst / IV-Accent'  THEN 2
                        WHEN a."Waarde" = 'Belastingdienst-CAP'  THEN 2
                        WHEN a."Waarde" = 'Belastingdienst, IV-organisatie'  THEN 2
                        WHEN a."Waarde" = 'Belastingdienst/Centrum Facilitaire Dienstverlening'  THEN 2
                        WHEN a."Waarde" = 'Belastingdienst Douane Nederland'  THEN 15
                        WHEN a."Waarde" = 'Centraal Bureau Rijvaardigheidsbewijzen'  THEN 4
                        WHEN a."Waarde" = 'Centraal Justitieel Incassobureau'  THEN 6
                        WHEN a."Waarde" = 'Immigratie- en Naturalisatiedienst'  THEN 17
                        WHEN a."Waarde" = 'Dienst Justis'  THEN 20
                        WHEN a."Waarde" = 'Kamer van Koophandel'  THEN 22
                        WHEN a."Waarde" = 'Koninklijke Bibliotheek'  THEN 25
                        WHEN a."Waarde" = 'Luchtverkeersleiding Nederland'  THEN 29
                        WHEN a."Waarde" = 'Nationaal Coordinator Groningen'  THEN 30
                        WHEN a."Waarde" = 'Openbaar Ministerie'  THEN 33
                        WHEN a."Waarde" = 'Raad voor de Rechtspraak'  THEN 35
                        WHEN a."Waarde" = 'Rijksdienst voor Identiteitsgevens'  THEN 37
                        WHEN a."Waarde" = 'Rijksdienst voor Identiteitsgegevens'  THEN 37
                        WHEN a."Waarde" = 'Rijksvastgoedbedrijf - RVB'  THEN 39
                        WHEN a."Waarde" = 'Sociale Verzekeringsbank'  THEN 42
                        WHEN a."Waarde" = 'Sociale Verzekeringsbank SVB'  THEN 42
                        WHEN a."Waarde" = 'Uitvoeringsinstituut Werknemersvezekeringen'  THEN 43
                        WHEN a."Waarde" = 'Uitvoeringsinstituut Werknemersverzekeringen'  THEN 43
                        WHEN a."Waarde" = 'Uitvoeringsinstituut Werknemers Verzekeringen'  THEN 43
                        WHEN a."Waarde" = 'Uitvoeringinstituut Werknemersverzekeringen UWV'  THEN 43
                        WHEN a."Waarde" = 'CAK'  THEN 3
                        WHEN a."Waarde" = 'CIZ'  THEN 7
                        WHEN a."Waarde" = 'CJIB'  THEN 6
                        WHEN a."Waarde" = 'DICTU'  THEN 8
                        WHEN a."Waarde" = 'DGVBR/SSC-ICT'  THEN 41
                        WHEN a."Waarde" = 'DJI'  THEN 9
                        WHEN a."Waarde" = 'Dienst Uitvoering Subsidies'  THEN 12
                        WHEN a."Waarde" = 'Het Kadaster'  THEN 21
                        WHEN a."Waarde" = 'IND'  THEN 17
                        WHEN a."Waarde" = 'KNMI'  THEN 24
                        WHEN a."Waarde" = 'LVNL'  THEN 29
                        WHEN a."Waarde" = 'NVWA'  THEN 32
                        WHEN a."Waarde" = 'RDW'  THEN 13
                        WHEN a."Waarde" = 'RVO'  THEN 38
                        WHEN a."Waarde" = 'RVO.nl'  THEN 38
                        WHEN a."Waarde" = 'RvIG'  THEN 37
                        WHEN a."Waarde" = 'SVB'  THEN 42
                        WHEN a."Waarde" = 'UWV'  THEN 43
                        WHEN a."Waarde" = 'Agentschap Telecom'  THEN 1
                        WHEN a."Waarde" = 'Belastingdienst'  THEN 2
                        WHEN a."Waarde" = 'Centraal Administratie Kantoor (CAK)'  THEN 3
                        WHEN a."Waarde" = 'Centraal Bureau Rijvaardigheidsbewijzen (CBR)'  THEN 4
                        WHEN a."Waarde" = 'Centraal Bureau voor de Statistiek (CBS)'  THEN 5
                        WHEN a."Waarde" = 'Centraal Justitieel Incassobureau (CJIB)'  THEN 6
                        WHEN a."Waarde" = 'Centrum indicatiestelling zorg (CIZ)'  THEN 7
                        WHEN a."Waarde" = 'Dienst ICT Uitvoering (DICTU)'  THEN 8
                        WHEN a."Waarde" = 'Dienst Justitiële Inrichtingen'  THEN 9
                        WHEN a."Waarde" = 'Dienst Terugkeer en Vertrek'  THEN 10
                        WHEN a."Waarde" = 'Dienst Uitvoering Onderwijs (DUO)'  THEN 11
                        WHEN a."Waarde" = 'Dienst Uitvoering Subsidies aan Instellingen (DUS-I)'  THEN 12
                        WHEN a."Waarde" = 'Dienst Wegverkeer (RDW)'  THEN 13
                        WHEN a."Waarde" = 'Directie Consulaire zaken en Visumbeleid (DCV)'  THEN 14
                        WHEN a."Waarde" = 'Douane'  THEN 15
                        WHEN a."Waarde" = 'Generale Thesaurie'  THEN 16
                        WHEN a."Waarde" = 'Immigratie- en Naturalisatiedienst (IND)'  THEN 17
                        WHEN a."Waarde" = 'Inspectie Gezondheidszorg en Jeugd (IGJ)'  THEN 18
                        WHEN a."Waarde" = 'Inspectie Leefomgeving en Transport'  THEN 19
                        WHEN a."Waarde" = 'Justis'  THEN 20
                        WHEN a."Waarde" = 'Kadaster'  THEN 21
                        WHEN a."Waarde" = 'Kamer van Koophandel (KvK)'  THEN 22
                        WHEN a."Waarde" = 'Kiesraad'  THEN 23
                        WHEN a."Waarde" = 'Koninklijk Nederlands Meteorologisch Instituut (KNMI)'  THEN 24
                        WHEN a."Waarde" = 'Koninklijke Bibliotheek (KB)'  THEN 25
                        WHEN a."Waarde" = 'Koninklijke Marechaussee'  THEN 26
                        WHEN a."Waarde" = 'Kustwacht'  THEN 27
                        WHEN a."Waarde" = 'Logius'  THEN 28
                        WHEN a."Waarde" = 'Luchtverkeersleiding Nederland (LVNL)'  THEN 29
                        WHEN a."Waarde" = 'Nationaal Coördinator Groningen'  THEN 30
                        WHEN a."Waarde" = 'Nederlands Forensisch Instituut'  THEN 31
                        WHEN a."Waarde" = 'Nederlandse Voedsel-en Warenautoriteit (NVWA)'  THEN 32
                        WHEN a."Waarde" = 'Openbaar Ministerie (OM)'  THEN 33
                        WHEN a."Waarde" = 'Organisatie en Personeel Rijk (P-Direkt)'  THEN 34
                        WHEN a."Waarde" = 'Raad voor de rechtspraak'  THEN 35
                        WHEN a."Waarde" = 'Rijksdienst voor het Cultureel Erfgoed'  THEN 36
                        WHEN a."Waarde" = 'Rijksdienst voor Identiteitsgegevens (RvIG)'  THEN 37
                        WHEN a."Waarde" = 'Rijksdienst voor Ondernemend Nederland (RVO)'  THEN 38
                        WHEN a."Waarde" = 'Rijksvastgoedbedrijf (RVB)'  THEN 39
                        WHEN a."Waarde" = 'Rijkswaterstaat'  THEN 40
                        WHEN a."Waarde" = 'Shared Service Center ICT (SSC-ICT)'  THEN 41
                        WHEN a."Waarde" = 'Sociale Verzekeringsbank (SVB)'  THEN 42
                        WHEN a."Waarde" = 'Uitvoeringsinstituut Werknemersverzekeringen (UWV)'  THEN 43            ELSE NULL
                    END as neworganisatieid,
                    pv_1."ProjectId",
                    il."Id" AS "IndicatorLijstId",
                    il."MeervoudsNaam" AS "IndicatorLijstMeervoudsNaam",
                    il."EnkelFormulier" AS "IndicatorLijstEnkelFormulier",
                    f."Id" AS "FormulierId",
                    f."AanmaakDatum" AS "FormulierAanmaakDatum",
                    i."Titel" AS "IndicatorTitel"
                FROM (((((("ProjectVersie" pv_1
                     JOIN "FormulierProjectVersie" fpv ON ((fpv."ProjectVersiesId" = pv_1."Id")))
                     JOIN "Project" project ON ((pv_1."ProjectId" = project."Id")))
                     JOIN "Formulier" f ON ((f."Id" = fpv."FormulierenId")))
                     JOIN "Antwoord" a ON ((a."FormulierId" = f."Id")))
                     JOIN "Indicator" i ON ((i."Id" = a."IndicatorId")))
                     JOIN "IndicatorLijst" il ON ((il."Id" = i."IndicatorLijstId"))
                     LEFT JOIN "Organisatie" organisatie 
                            ON 
                            --(a."Waarde" = organisatie."Naam"  )
                            SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(a."Waarde",'Rijksdienst voor ',''),'Centraal Bureau ',''),'Dienst Uitvoering ',''),'Koninklijk',''),'Nederlands',''),'Inspectie ',''),'Centraal ',''),'Dienst ',''), 0, 11)
                            = 
                            SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(organisatie."Naam",'Rijksdienst voor ',''),'Centraal Bureau ',''),'Dienst Uitvoering ',''),'Koninklijk',''),'Nederlands',''),'Inspectie ',''),'Centraal ',''),'Dienst ',''), 0, 11)
                            
                     )
                    where "IndicatorId" = 24
            ) as binnen
        group by projectnummer
        order by projectnummer
        ) as buiten
        WHERE "Project"."Nummer" = buiten.projectnummer
        ;

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230315145835_UpdateOrganisaties', '6.0.13');

        COMMIT;
        
    """
    op.execute(upgrade_query)
    op.execute("SET search_path TO public")


def downgrade() -> None:
    downgrade_query = """

        START TRANSACTION;

        DROP VIEW IF EXISTS "vProjectAgg";
        
        UPDATE public."Project" SET "OrganisatieId" = NULL;


        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '2849eb9c-52bf-4d27-bdc7-649dd0028de1', "SecurityStamp" = '7cf202da-ea68-4ac2-8371-0cc79a828ded'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '7b612ec9-4bfa-4172-950f-086988476dd6', "SecurityStamp" = '11cdffdd-c767-4223-8ec3-2f5200eb2fc9'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '0a385235-fc3d-42f3-9309-0be93a861ba6', "SecurityStamp" = '5a7e558f-eae4-4275-acd5-f9286d378640'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'c52b3d39-6f52-42ea-bd7f-ad45d58dde30', "SecurityStamp" = 'afa86ff5-21b1-4978-a241-77c3a345dce6'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = 'c801496c-7b9a-42df-acb4-973ed0b8b693'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230315145835_UpdateOrganisaties';

        COMMIT;

        START TRANSACTION;

        DELETE FROM "Organisatie"
        WHERE "Id" = 1;

        DELETE FROM "Organisatie"
        WHERE "Id" = 2;

        DELETE FROM "Organisatie"
        WHERE "Id" = 3;

        DELETE FROM "Organisatie"
        WHERE "Id" = 4;

        DELETE FROM "Organisatie"
        WHERE "Id" = 5;

        DELETE FROM "Organisatie"
        WHERE "Id" = 6;

        DELETE FROM "Organisatie"
        WHERE "Id" = 7;

        DELETE FROM "Organisatie"
        WHERE "Id" = 8;

        DELETE FROM "Organisatie"
        WHERE "Id" = 9;

        DELETE FROM "Organisatie"
        WHERE "Id" = 10;

        DELETE FROM "Organisatie"
        WHERE "Id" = 11;

        DELETE FROM "Organisatie"
        WHERE "Id" = 12;

        DELETE FROM "Organisatie"
        WHERE "Id" = 13;

        DELETE FROM "Organisatie"
        WHERE "Id" = 14;

        DELETE FROM "Organisatie"
        WHERE "Id" = 15;

        DELETE FROM "Organisatie"
        WHERE "Id" = 16;

        DELETE FROM "Organisatie"
        WHERE "Id" = 17;

        DELETE FROM "Organisatie"
        WHERE "Id" = 18;

        DELETE FROM "Organisatie"
        WHERE "Id" = 19;

        DELETE FROM "Organisatie"
        WHERE "Id" = 20;

        DELETE FROM "Organisatie"
        WHERE "Id" = 21;

        DELETE FROM "Organisatie"
        WHERE "Id" = 22;

        DELETE FROM "Organisatie"
        WHERE "Id" = 23;

        DELETE FROM "Organisatie"
        WHERE "Id" = 24;

        DELETE FROM "Organisatie"
        WHERE "Id" = 25;

        DELETE FROM "Organisatie"
        WHERE "Id" = 26;

        DELETE FROM "Organisatie"
        WHERE "Id" = 27;

        DELETE FROM "Organisatie"
        WHERE "Id" = 28;

        DELETE FROM "Organisatie"
        WHERE "Id" = 29;

        DELETE FROM "Organisatie"
        WHERE "Id" = 30;

        DELETE FROM "Organisatie"
        WHERE "Id" = 31;

        DELETE FROM "Organisatie"
        WHERE "Id" = 32;

        DELETE FROM "Organisatie"
        WHERE "Id" = 33;

        DELETE FROM "Organisatie"
        WHERE "Id" = 34;

        DELETE FROM "Organisatie"
        WHERE "Id" = 35;

        DELETE FROM "Organisatie"
        WHERE "Id" = 36;

        DELETE FROM "Organisatie"
        WHERE "Id" = 37;

        DELETE FROM "Organisatie"
        WHERE "Id" = 38;

        DELETE FROM "Organisatie"
        WHERE "Id" = 39;

        DELETE FROM "Organisatie"
        WHERE "Id" = 40;

        DELETE FROM "Organisatie"
        WHERE "Id" = 41;

        DELETE FROM "Organisatie"
        WHERE "Id" = 42;

        DELETE FROM "Organisatie"
        WHERE "Id" = 43;

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '1ab9bbcb-db75-434c-9f5d-02c8bdee3b32', "SecurityStamp" = 'cb9d75ce-fb98-404d-affd-303b3bd7fc3f'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '274d5473-27cf-4e20-b6f3-c95c974dabe7', "SecurityStamp" = '05711243-e0ff-4354-9aad-76c8744d911d'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'dfdcc757-758f-4632-97f5-c9a7c36adbf1', "SecurityStamp" = '6745fe68-7ce5-4452-b3b2-4f5eeb649d8a'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '8e4e32b2-8d91-4316-97b5-44794474bb8c', "SecurityStamp" = 'f083c682-00fd-47eb-ba1d-53eb0052b8f8'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '26febe77-cb07-4a5a-be8e-bcafa0fa4788'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230313135455_SeedOrganisaties';

        COMMIT;

        START TRANSACTION;

        ALTER TABLE "Project" DROP CONSTRAINT "FK_Project_Organisatie_OrganisatieId";

        DROP TABLE "GebruikerOrganisatie";

        DROP TABLE "Organisatie";

        DROP INDEX "IX_Project_OrganisatieId";

        ALTER TABLE "Project" DROP COLUMN "OrganisatieId";

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '5a7fd275-1d3e-455a-9d7b-96ec9214976a', "SecurityStamp" = '73544e53-346f-47a5-aadc-69397efb58f8'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '939cd7a9-63b4-447f-a5b1-237aff1315d1', "SecurityStamp" = '3df645c0-ce8f-441f-aec1-7fd1100788ea'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '50321f2a-6234-413c-8b8d-60cf85b76ffb', "SecurityStamp" = '696776a7-40d0-4c42-b558-d8e6ac4ab0bc'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'e36b0b56-05f1-4118-8efe-06ab99240b0a', "SecurityStamp" = '2a192426-8540-45eb-bceb-d7fb994eaeed'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '43efe5c4-7327-4af8-8936-a2ee36804ea4'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230306090830_AddOrganisatieTable';

        COMMIT;

        
    """
    op.execute(downgrade_query)
    op.execute("SET search_path TO public")
