"""AddIsAfgeslotenToProjectVersie To ModifyIndicators

Revsion ID: ad4824c9c1a0
Revises: df7dfe4f1d24
Create Date: 2023-02-10 14:23:00

upgrade script : script-migration AddIsAfgeslotenToProjectVersie ModifyIndicators
downgrade script : script-migration ModifyIndicators AddIsAfgeslotenToProjectVersie

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad4824c9c1a0"
down_revision = "df7dfe4f1d24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    upgrade_query = """
        START TRANSACTION;

        ALTER TABLE "AspNetUsers" DROP CONSTRAINT "FK_AspNetUsers_Ministerie_MinisterieId";

        DROP INDEX "IX_AspNetUsers_MinisterieId";

        CREATE TABLE "GebruikerMinisterie" (
        "GebruikersId" text NOT NULL,
        "MinisteriesId" integer NOT NULL,
        CONSTRAINT "PK_GebruikerMinisterie" PRIMARY KEY ("GebruikersId", "MinisteriesId"),
        CONSTRAINT "FK_GebruikerMinisterie_AspNetUsers_GebruikersId" FOREIGN KEY ("GebruikersId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GebruikerMinisterie_Ministerie_MinisteriesId" FOREIGN KEY ("MinisteriesId") REFERENCES "Ministerie" ("Id") ON DELETE CASCADE
        );

        INSERT INTO "public"."GebruikerMinisterie" ("GebruikersId", "MinisteriesId")SELECT  "Id", "MinisterieId"FROM  "public"."AspNetUsers" WHERE "MinisterieId" is not null;

        ALTER TABLE "AspNetUsers" DROP COLUMN "MinisterieId";

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'ae194a93-4cd2-4371-b66c-83aa6432190f', "SecurityStamp" = 'd2295710-00ef-44b5-b30f-49f639b05142'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'a31bb92e-9a74-41a5-85df-ef032a21bfc4', "SecurityStamp" = 'a2d42149-588e-47bb-a87b-0a336ea79efd'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '3f4c7343-bff4-4516-ada2-bda2c18fc7c9', "SecurityStamp" = 'bc0b8ad6-fffe-4ee0-b492-4b59e738c815'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '0dd056c6-7695-4713-b207-0c5c6ec51c1c', "SecurityStamp" = '09f1f7b7-2fb4-4878-b42d-29ef32c12f41'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '189de95c-bb3d-471b-a423-566fcf560efe'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        CREATE INDEX "IX_GebruikerMinisterie_MinisteriesId" ON "GebruikerMinisterie" ("MinisteriesId");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230208140141_AddGebruikerMinisterieTable', '6.0.10');

        COMMIT;

        START TRANSACTION;

        CREATE TABLE "ProjectVersiePreviewToken" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProjectVersieId" integer NOT NULL,
        "Token" text NULL,
        "AanmaakDatum" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_ProjectVersiePreviewToken" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProjectVersiePreviewToken_ProjectVersie_ProjectVersieId" FOREIGN KEY ("ProjectVersieId") REFERENCES "ProjectVersie" ("Id") ON DELETE CASCADE
        );

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'b9b65c8f-2263-4712-b909-498f136da866', "SecurityStamp" = '93267449-a325-432c-8ef2-7b6089412e80'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'b79c1c35-0e75-4fd8-990e-f4398a0fe207', "SecurityStamp" = '7fd7c35a-b399-4eb4-873d-017582d16602'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'ae60e03e-42e3-46a8-a7f5-2fc663658fc8', "SecurityStamp" = 'd985033b-10f9-4a50-aaeb-0e1133929151'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'f4df3659-cc5b-45a1-981e-e0fd79df6b41', "SecurityStamp" = '4d17ab57-c677-46cc-8d7c-b5b688a05e8c'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '5002e245-3f55-4117-9f86-566e2cdd93c1'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        CREATE INDEX "IX_ProjectVersiePreviewToken_ProjectVersieId" ON "ProjectVersiePreviewToken" ("ProjectVersieId");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230210103433_AddProjectVersiePreviewToken', '6.0.10');

        COMMIT;

        START TRANSACTION;

        CREATE TABLE "Tabeleigenschap" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Titel" text NOT NULL,
        "Type" integer NOT NULL,
        "TabelIndicatorId" integer NOT NULL,
        "Index" integer NOT NULL,
        "IsTotal" boolean NOT NULL,
        CONSTRAINT "PK_Tabeleigenschap" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tabeleigenschap_Indicator_TabelIndicatorId" FOREIGN KEY ("TabelIndicatorId") REFERENCES "Indicator" ("Id") ON DELETE CASCADE
        );

        CREATE TABLE "TabeleigenschapIndicator" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IndicatorId" integer NOT NULL,
        "RijId" integer NULL,
        "KolomId" integer NULL,
        CONSTRAINT "PK_TabeleigenschapIndicator" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TabeleigenschapIndicator_Indicator_IndicatorId" FOREIGN KEY ("IndicatorId") REFERENCES "Indicator" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TabeleigenschapIndicator_Tabeleigenschap_KolomId" FOREIGN KEY ("KolomId") REFERENCES "Tabeleigenschap" ("Id"),
        CONSTRAINT "FK_TabeleigenschapIndicator_Tabeleigenschap_RijId" FOREIGN KEY ("RijId") REFERENCES "Tabeleigenschap" ("Id")
        );

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'adc92501-966a-4c31-bb6a-055f245c7c62', "SecurityStamp" = '6f1b6968-db1a-4dfe-ac36-b07d5232536d'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'f7b24b08-e3c0-4005-a22d-c373d7c2679b', "SecurityStamp" = '1adbba35-bbd3-470c-a315-a2e00e95cc81'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'c96d4f10-83e8-4e9d-a999-231f6df244da', "SecurityStamp" = 'e34d4840-42d4-4457-bd6e-475799530c52'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'b3861523-9af7-41c9-9e55-1de6dff9e082', "SecurityStamp" = '20b4faa1-606f-4a1e-84be-f66dc1e0c893'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = 'b2023203-f21a-4e1d-b6e8-c994f9bd9648'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        CREATE INDEX "IX_Tabeleigenschap_TabelIndicatorId" ON "Tabeleigenschap" ("TabelIndicatorId");

        CREATE UNIQUE INDEX "IX_TabeleigenschapIndicator_IndicatorId" ON "TabeleigenschapIndicator" ("IndicatorId");

        CREATE INDEX "IX_TabeleigenschapIndicator_KolomId" ON "TabeleigenschapIndicator" ("KolomId");

        CREATE INDEX "IX_TabeleigenschapIndicator_RijId" ON "TabeleigenschapIndicator" ("RijId");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230210110025_AddTabeleigenschapTables', '6.0.10');

        COMMIT;

        START TRANSACTION;

        ALTER TABLE "Tabeleigenschap" RENAME COLUMN "Type" TO "TypeId";

        ALTER TABLE "ProjectVersie" RENAME COLUMN "Status" TO "StatusId";

        ALTER TABLE "Indicator" RENAME COLUMN "AntwoordType" TO "AntwoordTypeId";

        ALTER TABLE "ProjectVersie" ADD "ProjectVersieStatusId" integer NULL;

        CREATE TABLE "AntwoordType" (
        "Id" integer NOT NULL,
        "Naam" text NULL,
        CONSTRAINT "PK_AntwoordType" PRIMARY KEY ("Id")
        );

        CREATE TABLE "ProjectVersieStatus" (
        "Id" integer NOT NULL,
        "Naam" text NULL,
        CONSTRAINT "PK_ProjectVersieStatus" PRIMARY KEY ("Id")
        );

        CREATE TABLE "TabeleigenschapType" (
        "Id" integer NOT NULL,
        "Naam" text NULL,
        CONSTRAINT "PK_TabeleigenschapType" PRIMARY KEY ("Id")
        );

        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (0, 'Tekst');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (1, 'Getal');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (2, 'Datum');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (3, 'EnkeleKeuze');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (4, 'MeerKeuze');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (5, 'Tussenkopje');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (6, 'EnkeleKeuzeLijst');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (7, 'Tekstveld');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (8, 'Bedrag');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (9, 'Tabel');
        INSERT INTO "AntwoordType" ("Id", "Naam")
        VALUES (10, 'Tabelcel');

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '56b22d70-73e3-4673-87c2-22a4a3f07d7e', "SecurityStamp" = '172752ee-62a6-49fb-8f17-3c8e054bf063'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'bfa40e18-c182-40d6-90ae-dc8f94969e8d', "SecurityStamp" = '7c5ff761-a324-4c19-bb23-e9b6a66b7cec'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '738ca3df-56d3-4fe9-a09e-7ccfcc169e91', "SecurityStamp" = '59d644a6-56f9-4501-94dc-2d3e5c45f709'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '35665ef7-672b-44ee-9992-2f7b0fa7f57f', "SecurityStamp" = '309d1f4c-a9d2-44cb-856a-44a4597eeca5'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '37b95883-60e3-4c7e-9e27-b48a08270fea'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        INSERT INTO "ProjectVersieStatus" ("Id", "Naam")
        VALUES (0, 'Geen');
        INSERT INTO "ProjectVersieStatus" ("Id", "Naam")
        VALUES (1, 'Concept');
        INSERT INTO "ProjectVersieStatus" ("Id", "Naam")
        VALUES (2, 'Gecontroleerd');
        INSERT INTO "ProjectVersieStatus" ("Id", "Naam")
        VALUES (3, 'Gepubliceerd');

        INSERT INTO "TabeleigenschapType" ("Id", "Naam")
        VALUES (0, 'Rij');
        INSERT INTO "TabeleigenschapType" ("Id", "Naam")
        VALUES (1, 'Kolom');

        CREATE INDEX "IX_Tabeleigenschap_TypeId" ON "Tabeleigenschap" ("TypeId");

        CREATE INDEX "IX_ProjectVersie_ProjectVersieStatusId" ON "ProjectVersie" ("ProjectVersieStatusId");

        CREATE INDEX "IX_Indicator_AntwoordTypeId" ON "Indicator" ("AntwoordTypeId");

        ALTER TABLE "Indicator" ADD CONSTRAINT "FK_Indicator_AntwoordType_AntwoordTypeId" FOREIGN KEY ("AntwoordTypeId") REFERENCES "AntwoordType" ("Id") ON DELETE CASCADE;

        ALTER TABLE "ProjectVersie" ADD CONSTRAINT "FK_ProjectVersie_ProjectVersieStatus_ProjectVersieStatusId" FOREIGN KEY ("ProjectVersieStatusId") REFERENCES "ProjectVersieStatus" ("Id");

        ALTER TABLE "Tabeleigenschap" ADD CONSTRAINT "FK_Tabeleigenschap_TabeleigenschapType_TypeId" FOREIGN KEY ("TypeId") REFERENCES "TabeleigenschapType" ("Id") ON DELETE CASCADE;

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230210124353_AddEnumValuesToDatabase', '6.0.10');

        COMMIT;

        START TRANSACTION;

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '7285f113-6aa7-40b2-8060-032a619de587', "SecurityStamp" = '08705f01-0479-4d73-a2e0-a3704c047b2a'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '3a844287-b328-4e09-965e-f64664871cee', "SecurityStamp" = '1ea4d7f2-d207-4816-ad48-b2ef272e8f60'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'ae807691-f514-4e29-bbaa-3c0ab482aa90', "SecurityStamp" = '16d5d57e-aa98-4b49-ac16-855037d14b89'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '8db51e9a-0b7a-45ee-99bb-db47a41f7a55', "SecurityStamp" = '8ade73b8-774a-4c93-9cfa-3aef60b6313c'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = 'a37d16aa-2d4b-4060-a0cb-61cc7128a94d'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        UPDATE "public"."Indicator"
        SET "IndicatorLijstId"='a424c56c-e3e0-451a-bd0c-4f1c2d2108f3', "Index"='1'
        WHERE ("public"."Indicator"."Id" = 58);
        UPDATE "public"."Indicator"
        SET "Titel"='Peildatum'
        WHERE ("public"."Indicator"."Id" = 59);
        UPDATE "public"."Indicator"
        SET "Index"='3', "IndicatorLijstId"='a424c56c-e3e0-451a-bd0c-4f1c2d2108f3', "Titel"='Actueel geschatte einddatum'
        WHERE ("public"."Indicator"."Id" = 20);
        UPDATE "public"."Indicator"
        SET "VerwijderDatum"='2023-02-09 00:00:00', "IndicatorLijstId"='a424c56c-e3e0-451a-bd0c-4f1c2d2108f3'
        WHERE ("public"."Indicator"."Id" = 34);
        UPDATE "public"."Indicator"
        SET "Index"='2', "IndicatorLijstId"='a424c56c-e3e0-451a-bd0c-4f1c2d2108f3', "Titel"='Toelichting'
        WHERE ("public"."Indicator"."Id" = 33);
        UPDATE "public"."Indicator"
        SET "Index"='4', "AntwoordTypeId"='8'
        WHERE ("public"."Indicator"."Id" = 60);
        UPDATE "public"."Indicator"
        SET "Index"='5', "AntwoordTypeId"='8'
        WHERE ("public"."Indicator"."Id" = 61);
        UPDATE "public"."Indicator"
        SET "Index"='6', "AntwoordTypeId"='8'
        WHERE ("public"."Indicator"."Id" = 62);
        UPDATE "public"."Indicator"
        SET "VerwijderDatum"='2023-02-09 00:00:00', "IndicatorLijstId"='a424c56c-e3e0-451a-bd0c-4f1c2d2108f3'
        WHERE ("public"."Indicator"."Id" = 19);
        UPDATE "public"."Indicator"
        SET "Index"='7', "AntwoordTypeId"='8'
        WHERE ("public"."Indicator"."Id" = 63);
        UPDATE "public"."Indicator"
        SET "Index"='8', "AntwoordTypeId"='8'
        WHERE ("public"."Indicator"."Id" = 64);
        UPDATE "public"."Indicator"
        SET "Index"='9', "AntwoordTypeId"='8'
        WHERE ("public"."Indicator"."Id" = 65);
        INSERT INTO "public"."Indicator" ("IndicatorLijstId", "Index", "Vereist", "AntwoordTypeId", "Titel", "VerwijderDatum", "Toelichting", "AanmaakDatum") VALUES ('9dd9f735-746c-44ab-beba-42c1b3d7d4e0','2','false','2','Datum','0001-01-01 00:00:00','','2023-02-09 09:00:00');
        UPDATE "public"."Indicator"
        SET "AntwoordTypeId"='4'
        WHERE ("public"."Indicator"."Id" = 21);
        UPDATE "public"."Indicator"
        SET "AntwoordTypeId"='4'
        WHERE ("public"."Indicator"."Id" = 22);
        UPDATE "public"."Indicator"
        SET "AntwoordTypeId"='4'
        WHERE ("public"."Indicator"."Id" = 17);
        UPDATE "public"."Indicator"
        SET "Titel"='Organisatie'
        WHERE ("public"."Indicator"."Id" = 24);
        DELETE FROM "public"."IndicatorLijst"
        WHERE ("public"."IndicatorLijst"."Id" = '803853aa-50b6-4187-804f-d2fc11d1e546');
        UPDATE "public"."IndicatorLijst"
        SET "Naam"='Doorlooptijd en Kosten', "MeervoudsNaam"='Doorlooptijd en Kosten'
        WHERE ("public"."IndicatorLijst"."Id" = 'a424c56c-e3e0-451a-bd0c-4f1c2d2108f3');
        DELETE FROM "public"."IndicatorLijst"
        WHERE ("public"."IndicatorLijst"."Id" = '36a40611-758f-4fe1-83bc-7036d0ef7604');
        UPDATE "public"."AntwoordOptie"
        SET "Waarde"='Herijking'
        WHERE ("public"."AntwoordOptie"."Id" = 599);
        UPDATE "public"."AntwoordOptie"
        SET "Waarde"='Rapportage'
        WHERE ("public"."AntwoordOptie"."Id" = 600);
        UPDATE "public"."AntwoordOptie"
        SET "Waarde"='Initieel'
        WHERE ("public"."AntwoordOptie"."Id" = 601);
        UPDATE "public"."IndicatorLijst"
        SET "Index"='5'
        WHERE ("public"."IndicatorLijst"."Id" = '2997e04a-5d85-40ac-afb8-690016c124e3');
        UPDATE "public"."IndicatorLijst"
        SET "Index"='6'
        WHERE ("public"."IndicatorLijst"."Id" = 'a424c56c-e3e0-451a-bd0c-4f1c2d2108f3');
        UPDATE "public"."IndicatorLijst"
        SET "Index"='7'
        WHERE ("public"."IndicatorLijst"."Id" = '5ebe3b64-21d0-4657-b8bc-531565c33a1e');

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20230210125850_ModifyIndicators', '6.0.10');

        COMMIT;

    """
    op.execute(upgrade_query)


def downgrade() -> None:
    downgrade_query = """
        DROP VIEW IF EXISTS "vProjectAgg";
        
        START TRANSACTION;

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '56b22d70-73e3-4673-87c2-22a4a3f07d7e', "SecurityStamp" = '172752ee-62a6-49fb-8f17-3c8e054bf063'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'bfa40e18-c182-40d6-90ae-dc8f94969e8d', "SecurityStamp" = '7c5ff761-a324-4c19-bb23-e9b6a66b7cec'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '738ca3df-56d3-4fe9-a09e-7ccfcc169e91', "SecurityStamp" = '59d644a6-56f9-4501-94dc-2d3e5c45f709'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '35665ef7-672b-44ee-9992-2f7b0fa7f57f', "SecurityStamp" = '309d1f4c-a9d2-44cb-856a-44a4597eeca5'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '37b95883-60e3-4c7e-9e27-b48a08270fea'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230210125850_ModifyIndicators';

        COMMIT;

        START TRANSACTION;

        ALTER TABLE "Indicator" DROP CONSTRAINT "FK_Indicator_AntwoordType_AntwoordTypeId";

        ALTER TABLE "ProjectVersie" DROP CONSTRAINT "FK_ProjectVersie_ProjectVersieStatus_ProjectVersieStatusId";

        ALTER TABLE "Tabeleigenschap" DROP CONSTRAINT "FK_Tabeleigenschap_TabeleigenschapType_TypeId";

        DROP TABLE "AntwoordType";

        DROP TABLE "ProjectVersieStatus" CASCADE;

        DROP TABLE "TabeleigenschapType";

        DROP INDEX "IX_Tabeleigenschap_TypeId";

        DROP INDEX "IX_ProjectVersie_ProjectVersieStatusId";

        DROP INDEX "IX_Indicator_AntwoordTypeId";

        ALTER TABLE "ProjectVersie" DROP COLUMN "ProjectVersieStatusId";

        ALTER TABLE "Tabeleigenschap" RENAME COLUMN "TypeId" TO "Type";

        ALTER TABLE "ProjectVersie" RENAME COLUMN "StatusId" TO "Status";

        ALTER TABLE "Indicator" RENAME COLUMN "AntwoordTypeId" TO "AntwoordType";

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'adc92501-966a-4c31-bb6a-055f245c7c62', "SecurityStamp" = '6f1b6968-db1a-4dfe-ac36-b07d5232536d'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'f7b24b08-e3c0-4005-a22d-c373d7c2679b', "SecurityStamp" = '1adbba35-bbd3-470c-a315-a2e00e95cc81'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'c96d4f10-83e8-4e9d-a999-231f6df244da', "SecurityStamp" = 'e34d4840-42d4-4457-bd6e-475799530c52'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'b3861523-9af7-41c9-9e55-1de6dff9e082', "SecurityStamp" = '20b4faa1-606f-4a1e-84be-f66dc1e0c893'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = 'b2023203-f21a-4e1d-b6e8-c994f9bd9648'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230210124353_AddEnumValuesToDatabase';

        COMMIT;

        START TRANSACTION;

        DROP TABLE "TabeleigenschapIndicator";

        DROP TABLE "Tabeleigenschap";

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'b9b65c8f-2263-4712-b909-498f136da866', "SecurityStamp" = '93267449-a325-432c-8ef2-7b6089412e80'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'b79c1c35-0e75-4fd8-990e-f4398a0fe207', "SecurityStamp" = '7fd7c35a-b399-4eb4-873d-017582d16602'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'ae60e03e-42e3-46a8-a7f5-2fc663658fc8', "SecurityStamp" = 'd985033b-10f9-4a50-aaeb-0e1133929151'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'f4df3659-cc5b-45a1-981e-e0fd79df6b41', "SecurityStamp" = '4d17ab57-c677-46cc-8d7c-b5b688a05e8c'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '5002e245-3f55-4117-9f86-566e2cdd93c1'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230210110025_AddTabeleigenschapTables';

        COMMIT;

        START TRANSACTION;

        DROP TABLE "ProjectVersiePreviewToken";

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'ae194a93-4cd2-4371-b66c-83aa6432190f', "SecurityStamp" = 'd2295710-00ef-44b5-b30f-49f639b05142'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'a31bb92e-9a74-41a5-85df-ef032a21bfc4', "SecurityStamp" = 'a2d42149-588e-47bb-a87b-0a336ea79efd'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '3f4c7343-bff4-4516-ada2-bda2c18fc7c9', "SecurityStamp" = 'bc0b8ad6-fffe-4ee0-b492-4b59e738c815'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '0dd056c6-7695-4713-b207-0c5c6ec51c1c', "SecurityStamp" = '09f1f7b7-2fb4-4878-b42d-29ef32c12f41'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '189de95c-bb3d-471b-a423-566fcf560efe'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230210103433_AddProjectVersiePreviewToken';

        COMMIT;

        START TRANSACTION;

        ALTER TABLE "AspNetUsers" ADD "MinisterieId" integer NULL;

        UPDATE "public"."AspNetUsers"SET "MinisterieId" =( Select "GebruikerMinisterieId"."MinisteriesId"                        FROM                        (                            SELECT                                "GebruikersId",                                min("MinisteriesId") as "MinisteriesId"                            FROM "public"."GebruikerMinisterie"                            GROUP BY "GebruikersId"                        ) as "GebruikerMinisterieId"                        WHERE "public"."AspNetUsers"."Id" = "GebruikerMinisterieId"."GebruikersId"                    );

        DROP TABLE "GebruikerMinisterie";

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '8fca1f1e-c7df-4b69-a091-89a1b9a34e34', "MinisterieId" = 2, "SecurityStamp" = '47b9c740-99ad-49aa-b5e0-aabdabcac066'
        WHERE "Id" = '258f96f3-ef86-4c00-b9f8-1cee593fd158';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '562e95d1-0cce-4364-ae45-619d1c750bd1', "MinisterieId" = 2, "SecurityStamp" = '1f98ccc3-2827-4a6f-99e1-106bf0f66b94'
        WHERE "Id" = '971c5b84-ce6f-4d8e-b009-c0fbc9ea452b';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '6b86bf55-0e1b-4d03-a145-0febf2c89d5f', "SecurityStamp" = 'aeca4c1f-172d-4e4a-94cf-3cd0dd502294'
        WHERE "Id" = '992dca13-29cf-491c-9b94-4462cd3bb3eb';

        UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '041c1bdb-01c6-4188-b457-52e201fbbe15', "SecurityStamp" = '2b6d4c23-b1b0-4b1a-8588-89e1043a30a6'
        WHERE "Id" = 'bc6eee82-2c77-4c19-9505-1f9a9a5cd0fa';

        UPDATE "AspNetUsers" SET "SecurityStamp" = '1114de1f-7fef-490a-b948-e876d62d2115'
        WHERE "Id" = 'f544b9a8-fd3d-480e-8966-413996ccfaa4';

        CREATE INDEX "IX_AspNetUsers_MinisterieId" ON "AspNetUsers" ("MinisterieId");

        ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Ministerie_MinisterieId" FOREIGN KEY ("MinisterieId") REFERENCES "Ministerie" ("Id");

        DELETE FROM "__EFMigrationsHistory"
        WHERE "MigrationId" = '20230208140141_AddGebruikerMinisterieTable';

        COMMIT;
    """
    op.execute(downgrade_query)
