/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { IndicatorLijst } from './IndicatorLijst';
export type ProjectMetAlleMetricsEnIndicatorLijsten = {
    ProjectStatus: (string | null);
    HeeftAcICTAdvies: string;
    Onderwerp: (string | null);
    Dienstverlening: (string | null);
    MaatschappelijkeBaat: (string | null);
    Ontwikkelwijze: (string | null);
    SchattingEinddatumInitieel: (string | null);
    SchattingEinddatumActueel: (string | null);
    SchattingTotaleKostenInitieel: (number | null);
    SchattingTotaleKostenVorigJaar: (number | null);
    OverigeKostenDaadwerkelijk: (number | null);
    InternPersoneelDaadwerkelijk: (number | null);
    ExternPersoneelDaadwerkelijk: (number | null);
    UitbesteedWerkDaadwerkelijk: (number | null);
    InbesteedWerkDaadwerkelijk: (number | null);
    DataverbindingenDaadwerkelijk: (number | null);
    StandaardsoftwareDaadwerkelijk: (number | null);
    HardwareDaadwerkelijk: (number | null);
    HardwareSoftwareDaadwerkelijk: (number | null);
    OverigMaterieelDaadwerkelijk: (number | null);
    OverigeKostenActueel: (number | null);
    InternPersoneelActueel: (number | null);
    ExternPersoneelActueel: (number | null);
    UitbesteedWerkActueel: (number | null);
    InbesteedWerkActueel: (number | null);
    DataverbindingenActueel: (number | null);
    StandaardsoftwareActueel: (number | null);
    HardwareActueel: (number | null);
    HardwareSoftwareActueel: (number | null);
    OverigMaterieelActueel: (number | null);
    OverigeKostenInitieel: (number | null);
    InternPersoneelInitieel: (number | null);
    ExternPersoneelInitieel: (number | null);
    UitbesteedWerkInitieel: (number | null);
    InbesteedWerkInitieel: (number | null);
    DataverbindingenInitieel: (number | null);
    StandaardsoftwareInitieel: (number | null);
    HardwareInitieel: (number | null);
    HardwareSoftwareInitieel: (number | null);
    OverigMaterieelInitieel: (number | null);
    CumulatieveKostenHuidigJaar: (number | null);
    CumulatieveKostenVorigJaar: (number | null);
    PrognoseToekomstigeKosten: number;
    ActiefInJbrJaar: boolean;
    SoortICTActiviteit: (string | null);
    RedenenHerijkingen: string;
    AantalBaten: number;
    Ontwikkelpartijen: string;
    AantalBehaaldeMijlpalen: number;
    StartJaar: (number | null);
    EindJaar: (number | null);
    AantalAcICTAdviezen: number;
    VerschilEindatumInitieelActueelInJaren: (number | null);
    DoorlooptijdInitieel: (number | null);
    VerschilDoorlooptijdPct: number;
    ProjectId: string;
    Naam: string;
    Slug: string;
    ProjectVersieId: number;
    ProjectVersie: number;
    LegacyProjectId: (number | null);
    MinisterieNaam: string;
    MinisterieAfkorting: string;
    ProjectVersieWijzigingsDatum: string;
    ProjectVersieStatusNaam: string;
    ProjectVersieStatusId: number;
    StartDatum: (string | null);
    PeilDatum: (string | null);
    OrganisatieNaam: (string | null);
    IndicatorLijstWaardesGecorrigeerd: Array<IndicatorLijst>;
    ActiviteitId: string;
    Ministerie: string;
    DoorlooptijdActueel: (number | null);
    SchattingTotaleKostenHuidigJaar: number;
};

