--
-- PostgreSQL database dump
--

-- Dumped from database version 15.9
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgbouncer; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA pgbouncer;


--
-- Name: get_auth(text); Type: FUNCTION; Schema: pgbouncer; Owner: -
--

CREATE FUNCTION pgbouncer.get_auth(username text) RETURNS TABLE(username text, password text)
    LANGUAGE sql STABLE SECURITY DEFINER
    AS $_$
  SELECT rolname::TEXT, rolpassword::TEXT
  FROM pg_catalog.pg_authid
  WHERE pg_authid.rolname = $1
    AND pg_authid.rolcanlogin
    AND NOT pg_authid.rolsuper
    AND NOT pg_authid.rolreplication
    AND pg_authid.rolname <> '_crunchypgbouncer'
    AND (pg_authid.rolvaliduntil IS NULL OR pg_authid.rolvaliduntil >= CURRENT_TIMESTAMP)$_$;


--
-- Name: user_search(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.user_search(uname text) RETURNS TABLE(usename name, passwd text)
    LANGUAGE sql SECURITY DEFINER
    AS $_$SELECT usename, passwd FROM pg_catalog.pg_shadow WHERE usename=$1;$_$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Aandachtspunt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Aandachtspunt" (
    "Id" integer NOT NULL,
    "Type" character varying NOT NULL,
    "Waarde" character varying,
    "WijzigingsDatum" timestamp without time zone DEFAULT now() NOT NULL,
    "GewijzigdDoorGebruikerId" integer
);


--
-- Name: Aandachtspunt_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Aandachtspunt_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Aandachtspunt_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Aandachtspunt_Id_seq" OWNED BY public."Aandachtspunt"."Id";


--
-- Name: Antwoord; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Antwoord" (
    "Id" integer NOT NULL,
    "IndicatorId" integer NOT NULL,
    "Waarde" text,
    "FormulierId" uuid,
    "AanmaakDatum" timestamp without time zone NOT NULL,
    "WijzigingsDatum" timestamp without time zone NOT NULL,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "AangemaaktDoorGebruikerId" integer,
    "GewijzigdDoorGebruikerId" integer
);


--
-- Name: AntwoordOptie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AntwoordOptie" (
    "Id" integer NOT NULL,
    "Waarde" text NOT NULL,
    "IndicatorId" integer NOT NULL,
    "Index" integer NOT NULL
);


--
-- Name: AntwoordOptie_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AntwoordOptie" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AntwoordOptie_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AntwoordType; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AntwoordType" (
    "Id" integer NOT NULL,
    "Naam" text
);


--
-- Name: Antwoord_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Antwoord" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Antwoord_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- Name: Formulier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Formulier" (
    "Id" uuid NOT NULL,
    "Nummer" integer NOT NULL,
    "Status" integer NOT NULL,
    "AanmaakDatum" timestamp without time zone NOT NULL,
    "GebruikerId" text,
    "IndicatorLijstId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "WijzigingsDatum" timestamp without time zone DEFAULT '0001-01-01 00:00:00'::timestamp without time zone NOT NULL,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "AangemaaktDoorGebruikerId" integer,
    "GewijzigdDoorGebruikerId" integer
);


--
-- Name: FormulierProjectVersie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FormulierProjectVersie" (
    "Id" integer NOT NULL,
    "FormulierenId" uuid NOT NULL,
    "ProjectVersiesId" integer NOT NULL
);


--
-- Name: FormulierProjectVersie_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."FormulierProjectVersie" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FormulierProjectVersie_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Gebruiker; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Gebruiker" (
    "Id" integer NOT NULL,
    "Naam" character varying NOT NULL,
    "Actief" boolean DEFAULT true NOT NULL,
    "AanmaakDatum" timestamp with time zone NOT NULL,
    "WijzigingsDatum" timestamp with time zone NOT NULL,
    "KeycloakUserId" character varying
);


--
-- Name: GebruikerMinisterie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GebruikerMinisterie" (
    "GebruikersId" text NOT NULL,
    "MinisteriesId" integer NOT NULL
);


--
-- Name: GebruikerMinisterieNieuw; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GebruikerMinisterieNieuw" (
    "Id" integer NOT NULL,
    "GebruikerId" integer NOT NULL,
    "MinisterieId" integer NOT NULL,
    "AanmaakDatum" timestamp with time zone NOT NULL,
    "WijzigingsDatum" timestamp with time zone NOT NULL
);


--
-- Name: GebruikerMinisterieNieuw_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."GebruikerMinisterieNieuw_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: GebruikerMinisterieNieuw_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."GebruikerMinisterieNieuw_Id_seq" OWNED BY public."GebruikerMinisterieNieuw"."Id";


--
-- Name: GebruikerOrganisatie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GebruikerOrganisatie" (
    "GebruikersId" text NOT NULL,
    "OrganisatiesId" integer NOT NULL
);


--
-- Name: GebruikerOrganisatieNieuw; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GebruikerOrganisatieNieuw" (
    "Id" integer NOT NULL,
    "GebruikerId" integer NOT NULL,
    "OrganisatieId" integer NOT NULL,
    "AanmaakDatum" timestamp with time zone NOT NULL,
    "WijzigingsDatum" timestamp with time zone NOT NULL
);


--
-- Name: GebruikerOrganisatieNieuw_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."GebruikerOrganisatieNieuw_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: GebruikerOrganisatieNieuw_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."GebruikerOrganisatieNieuw_Id_seq" OWNED BY public."GebruikerOrganisatieNieuw"."Id";


--
-- Name: GebruikerProject; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GebruikerProject" (
    "GebruikersId" text NOT NULL,
    "ProjectenId" uuid NOT NULL
);


--
-- Name: GebruikerRol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GebruikerRol" (
    "Id" integer NOT NULL,
    "GebruikerId" integer NOT NULL,
    "RolId" integer NOT NULL,
    "AanmaakDatum" timestamp with time zone NOT NULL,
    "WijzigingsDatum" timestamp with time zone NOT NULL
);


--
-- Name: GebruikerRol_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."GebruikerRol_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: GebruikerRol_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."GebruikerRol_Id_seq" OWNED BY public."GebruikerRol"."Id";


--
-- Name: Gebruiker_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Gebruiker_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Gebruiker_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Gebruiker_Id_seq" OWNED BY public."Gebruiker"."Id";


--
-- Name: Indicator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Indicator" (
    "Id" integer NOT NULL,
    "Titel" text NOT NULL,
    "AntwoordTypeId" integer NOT NULL,
    "Vereist" boolean NOT NULL,
    "Index" integer NOT NULL,
    "VerwijderDatum" timestamp without time zone NOT NULL,
    "IndicatorLijstId" uuid NOT NULL,
    "Toelichting" text,
    "AanmaakDatum" timestamp without time zone NOT NULL,
    "IsLockable" boolean DEFAULT false NOT NULL
);


--
-- Name: IndicatorLijst; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."IndicatorLijst" (
    "Id" uuid NOT NULL,
    "Naam" text,
    "EnkelFormulier" boolean DEFAULT false NOT NULL,
    "Index" integer DEFAULT 0 NOT NULL,
    "MeervoudsNaam" text,
    "Vereist" boolean DEFAULT false NOT NULL,
    "IsLockable" boolean DEFAULT false NOT NULL
);


--
-- Name: Indicator_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Indicator" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Indicator_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ministerie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Ministerie" (
    "Id" integer NOT NULL,
    "Naam" text,
    "Afkorting" text
);


--
-- Name: Ministerie_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Ministerie" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ministerie_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Organisatie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Organisatie" (
    "Id" integer NOT NULL,
    "Naam" text,
    "MinisterieId" integer NOT NULL
);


--
-- Name: Organisatie_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Organisatie" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Organisatie_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Project" (
    "Id" uuid NOT NULL,
    "LaatsteVersieId" integer,
    "Nummer" integer NOT NULL,
    "Naam" text,
    "AanmaakDatum" timestamp without time zone NOT NULL,
    "WijzigingsDatum" timestamp without time zone NOT NULL,
    "MinisterieId" integer DEFAULT 1 NOT NULL,
    "OrganisatieId" integer,
    "IsGestart" boolean DEFAULT false NOT NULL,
    "Slug" character varying(255) NOT NULL,
    "LegacyProjectId" integer,
    "Beheerinformatie" character varying(500)
);


--
-- Name: ProjectVersie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ProjectVersie" (
    "Id" integer NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Versie" integer NOT NULL,
    "AanmaakDatum" timestamp without time zone NOT NULL,
    "WijzigingsDatum" timestamp without time zone NOT NULL,
    "StatusId" integer DEFAULT 0 NOT NULL,
    "Annotatie" text,
    "IsAfgesloten" boolean DEFAULT false NOT NULL,
    "ProjectVersieStatusId" integer,
    "IsLocked" boolean DEFAULT false NOT NULL,
    "AangemaaktDoorGebruikerId" integer,
    "GewijzigdDoorGebruikerId" integer
);


--
-- Name: ProjectVersiePreviewToken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ProjectVersiePreviewToken" (
    "Id" integer NOT NULL,
    "ProjectVersieId" integer NOT NULL,
    "Token" text,
    "AanmaakDatum" timestamp without time zone NOT NULL
);


--
-- Name: ProjectVersiePreviewToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ProjectVersiePreviewToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProjectVersiePreviewToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProjectVersieStatus; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ProjectVersieStatus" (
    "Id" integer NOT NULL,
    "Naam" text
);


--
-- Name: ProjectVersie_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ProjectVersie" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProjectVersie_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rol" (
    "Id" integer NOT NULL,
    "Naam" character varying NOT NULL,
    "AanmaakDatum" timestamp with time zone NOT NULL,
    "WijzigingsDatum" timestamp with time zone NOT NULL
);


--
-- Name: Rol_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."Rol_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: Rol_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."Rol_Id_seq" OWNED BY public."Rol"."Id";


--
-- Name: StatusChange; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."StatusChange" (
    "Id" integer NOT NULL,
    "AanmaakDatum" timestamp without time zone NOT NULL,
    "WijzigingsDatum" timestamp without time zone NOT NULL,
    "BeginDatum" timestamp without time zone NOT NULL,
    "EindDatum" timestamp without time zone,
    "ProjectVersieId" integer NOT NULL,
    "Status" integer NOT NULL,
    "GebruikerId" integer
);


--
-- Name: StatusChange_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."StatusChange" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StatusChange_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tabeleigenschap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Tabeleigenschap" (
    "Id" integer NOT NULL,
    "Titel" text NOT NULL,
    "TypeId" integer NOT NULL,
    "TabelIndicatorId" integer NOT NULL,
    "Index" integer NOT NULL,
    "IsTotal" boolean NOT NULL
);


--
-- Name: TabeleigenschapIndicator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."TabeleigenschapIndicator" (
    "Id" integer NOT NULL,
    "IndicatorId" integer NOT NULL,
    "RijId" integer,
    "KolomId" integer
);


--
-- Name: TabeleigenschapIndicator_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."TabeleigenschapIndicator" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TabeleigenschapIndicator_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TabeleigenschapType; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."TabeleigenschapType" (
    "Id" integer NOT NULL,
    "Naam" text
);


--
-- Name: Tabeleigenschap_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Tabeleigenschap" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tabeleigenschap_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ToegangWijziging; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ToegangWijziging" (
    "Id" integer NOT NULL,
    "GewijzigdVoorGebruikerId" integer NOT NULL,
    "GewijzigdDoorGebruikerId" integer,
    "Datum" timestamp with time zone NOT NULL,
    "Status" character varying NOT NULL,
    "MinisterieId" integer,
    "OrganisatieId" integer,
    "RolId" integer
);


--
-- Name: ToegangWijziging_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."ToegangWijziging_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ToegangWijziging_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."ToegangWijziging_Id_seq" OWNED BY public."ToegangWijziging"."Id";


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: ministerie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ministerie (
    ministerie_id integer NOT NULL,
    afkorting character varying NOT NULL,
    toegevoegd_op timestamp without time zone NOT NULL,
    gewijzigd_op timestamp without time zone
);


--
-- Name: ministerie_ministerie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.ministerie_ministerie_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ministerie_ministerie_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.ministerie_ministerie_id_seq OWNED BY public.ministerie.ministerie_id;


--
-- Name: project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project (
    project_id integer NOT NULL,
    naam character varying NOT NULL,
    startdatum timestamp without time zone NOT NULL,
    einddatum_initieel timestamp without time zone NOT NULL,
    einddatum_huidig timestamp without time zone NOT NULL,
    kosten_meerjarig_geschat_initieel double precision NOT NULL,
    prognose_toekomstige_kosten double precision NOT NULL,
    uitgaven_cumulatief double precision NOT NULL,
    status_id integer,
    ministerie_id integer,
    toegevoegd_op timestamp without time zone NOT NULL,
    gewijzigd_op timestamp without time zone,
    omschrijving character varying[]
);


--
-- Name: project_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.project_project_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: project_project_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.project_project_id_seq OWNED BY public.project.project_id;


--
-- Name: status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.status (
    status_id integer NOT NULL,
    omschrijving character varying NOT NULL,
    toegevoegd_op timestamp without time zone NOT NULL,
    gewijzigd_op timestamp without time zone
);


--
-- Name: status_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.status_status_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: status_status_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.status_status_id_seq OWNED BY public.status.status_id;


--
-- Name: vProjectAgg; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public."vProjectAgg" AS
 WITH projectversieattributen AS (
         SELECT pv_1."Id" AS "ProjectVersieId",
            pv_1."ProjectId",
            il."Id" AS "IndicatorLijstId",
            il."MeervoudsNaam" AS "IndicatorLijstMeervoudsNaam",
            il."EnkelFormulier" AS "IndicatorLijstEnkelFormulier",
            il."Index" AS "IndicatorLijstIndex",
            f."Id" AS "FormulierId",
            f."AanmaakDatum" AS "FormulierAanmaakDatum",
            i."Titel" AS "IndicatorTitel",
            i."Index" AS "IndicatorIndex",
            awty."Naam" AS "IndicatorAntwoordTypeNaam",
            a."Waarde",
                CASE
                    WHEN ((il."MeervoudsNaam" = 'Doorlooptijd en Kosten'::text) AND ((i."Titel" = 'Daadwerkelijk extern personeel'::text) OR (i."Titel" = 'Daadwerkelijk intern personeel'::text)) AND (i."Index" = 7)) THEN concat(i."Titel", ' (oud)')
                    WHEN ((il."MeervoudsNaam" = 'Doorlooptijd en Kosten'::text) AND ((i."Titel" = 'Daadwerkelijk extern personeel'::text) OR (i."Titel" = 'Daadwerkelijk intern personeel'::text)) AND (i."Index" = 6)) THEN concat(i."Titel", ' (nieuw)')
                    ELSE i."Titel"
                END AS "IndicatorTitelGecorrigeerd"
           FROM ((((((public."ProjectVersie" pv_1
             LEFT JOIN public."FormulierProjectVersie" fpv ON ((fpv."ProjectVersiesId" = pv_1."Id")))
             LEFT JOIN public."Formulier" f ON ((f."Id" = fpv."FormulierenId")))
             LEFT JOIN public."Antwoord" a ON ((a."FormulierId" = f."Id")))
             LEFT JOIN public."Indicator" i ON ((i."Id" = a."IndicatorId")))
             LEFT JOIN public."IndicatorLijst" il ON ((il."Id" = i."IndicatorLijstId")))
             LEFT JOIN public."AntwoordType" awty ON ((awty."Id" = i."AntwoordTypeId")))
        ), projectversieattributenagg AS (
         SELECT projectversieattributen."ProjectVersieId",
            projectversieattributen."ProjectId",
            projectversieattributen."FormulierId",
            projectversieattributen."FormulierAanmaakDatum",
            projectversieattributen."IndicatorLijstId",
            projectversieattributen."IndicatorLijstMeervoudsNaam",
            projectversieattributen."IndicatorLijstEnkelFormulier",
            projectversieattributen."IndicatorLijstIndex",
            json_agg(json_build_object('IndicatorTitel', projectversieattributen."IndicatorTitelGecorrigeerd", 'IndicatorIndex', projectversieattributen."IndicatorIndex", 'Waarde', projectversieattributen."Waarde", 'IndicatorAntwoordTypeNaam', projectversieattributen."IndicatorAntwoordTypeNaam")) AS "FormulierWaardes"
           FROM projectversieattributen
          GROUP BY projectversieattributen."ProjectId", projectversieattributen."ProjectVersieId", projectversieattributen."FormulierId", projectversieattributen."FormulierAanmaakDatum", projectversieattributen."IndicatorLijstId", projectversieattributen."IndicatorLijstMeervoudsNaam", projectversieattributen."IndicatorLijstEnkelFormulier", projectversieattributen."IndicatorLijstIndex"
        ), projectversieindicatorlijstagg AS (
         SELECT projectversieattributenagg."ProjectVersieId",
            projectversieattributenagg."ProjectId",
            projectversieattributenagg."IndicatorLijstId",
            projectversieattributenagg."IndicatorLijstMeervoudsNaam",
            projectversieattributenagg."IndicatorLijstEnkelFormulier",
            projectversieattributenagg."IndicatorLijstIndex",
            COALESCE(json_agg(json_build_object('FormulierId', projectversieattributenagg."FormulierId", 'FormulierAanmaakDatum', projectversieattributenagg."FormulierAanmaakDatum", 'FormulierWaardes', projectversieattributenagg."FormulierWaardes")) FILTER (WHERE (projectversieattributenagg."FormulierId" IS NOT NULL)), '[]'::json) AS "Formulier"
           FROM projectversieattributenagg
          GROUP BY projectversieattributenagg."ProjectVersieId", projectversieattributenagg."ProjectId", projectversieattributenagg."IndicatorLijstId", projectversieattributenagg."IndicatorLijstMeervoudsNaam", projectversieattributenagg."IndicatorLijstEnkelFormulier", projectversieattributenagg."IndicatorLijstIndex"
        ), projectversieagg AS (
         SELECT projectversieindicatorlijstagg."ProjectVersieId",
            projectversieindicatorlijstagg."ProjectId",
            COALESCE(json_agg(json_build_object('IndicatorLijstId', projectversieindicatorlijstagg."IndicatorLijstId", 'IndicatorLijstMeervoudsNaam', projectversieindicatorlijstagg."IndicatorLijstMeervoudsNaam", 'IndicatorLijstEnkelFormulier', projectversieindicatorlijstagg."IndicatorLijstEnkelFormulier", 'IndicatorLijstIndex', projectversieindicatorlijstagg."IndicatorLijstIndex", 'Formulier', projectversieindicatorlijstagg."Formulier")) FILTER (WHERE (projectversieindicatorlijstagg."IndicatorLijstId" IS NOT NULL)), '[]'::json) AS "IndicatorLijstWaardes",
            COALESCE(array_agg(projectversieindicatorlijstagg."IndicatorLijstMeervoudsNaam") FILTER (WHERE (projectversieindicatorlijstagg."IndicatorLijstMeervoudsNaam" IS NOT NULL)), '{}'::text[]) AS "IndicatorLijstBeschikbaar"
           FROM projectversieindicatorlijstagg
          GROUP BY projectversieindicatorlijstagg."ProjectVersieId", projectversieindicatorlijstagg."ProjectId"
        ), projectversiesamenvatting AS (
         SELECT projectversieattributen."ProjectVersieId",
            json_object_agg(projectversieattributen."IndicatorTitel", projectversieattributen."Waarde") AS "ProjectSamenvatting"
           FROM projectversieattributen
          WHERE (projectversieattributen."IndicatorLijstMeervoudsNaam" = ANY (ARRAY['Algemeen'::text, 'Peildatum en Status'::text]))
          GROUP BY projectversieattributen."ProjectVersieId"
        )
 SELECT p."Id",
    p."LaatsteVersieId",
    p."Nummer",
    p."Naam",
    p."AanmaakDatum",
    p."WijzigingsDatum",
    p."MinisterieId",
    p."OrganisatieId",
    p."IsGestart",
    p."Slug",
    p."LegacyProjectId",
    p."Beheerinformatie",
    pvs."ProjectSamenvatting" AS "Samenvatting",
    pv."Versie" AS "ProjectVersie",
    pvst."Naam" AS "ProjectVersieStatusNaam",
    pvst."Id" AS "ProjectVersieStatusId",
    pvagg."ProjectVersieId",
    pvagg."ProjectId",
    pvagg."IndicatorLijstWaardes",
    pvagg."IndicatorLijstBeschikbaar",
    TRIM(BOTH '"'::text FROM ((pvs."ProjectSamenvatting" -> 'Onderwerp'::text))::text) AS "Onderwerp",
    TRIM(BOTH '"'::text FROM ((pvs."ProjectSamenvatting" -> 'Status'::text))::text) AS "ProjectStatus",
    TRIM(BOTH '"'::text FROM ((pvs."ProjectSamenvatting" -> 'Startdatum'::text))::text) AS "StartDatum",
    to_date(TRIM(BOTH '"'::text FROM ((pvs."ProjectSamenvatting" -> 'Peildatum'::text))::text), 'YYYY-MM-DD'::text) AS "PeilDatum",
    EXTRACT(year FROM to_date(TRIM(BOTH '"'::text FROM ((pvs."ProjectSamenvatting" -> 'Peildatum'::text))::text), 'YYYY-MM-DD'::text)) AS "PeilDatumJaar",
    pv."WijzigingsDatum" AS "ProjectVersieWijzigingsDatum",
    m."Naam" AS "MinisterieNaam",
    m."Afkorting" AS "MinisterieAfkorting",
    o."Naam" AS "OrganisatieNaam"
   FROM ((((((projectversieagg pvagg
     JOIN public."Project" p ON ((p."Id" = pvagg."ProjectId")))
     LEFT JOIN projectversiesamenvatting pvs ON ((pvs."ProjectVersieId" = pvagg."ProjectVersieId")))
     JOIN public."ProjectVersie" pv ON ((pv."Id" = pvagg."ProjectVersieId")))
     JOIN public."Ministerie" m ON ((m."Id" = p."MinisterieId")))
     JOIN public."ProjectVersieStatus" pvst ON ((pvst."Id" = pv."StatusId")))
     LEFT JOIN public."Organisatie" o ON ((o."Id" = p."OrganisatieId")));


--
-- Name: vProjectAggStatus; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public."vProjectAggStatus" AS
 WITH projectversieattributen AS (
         SELECT pv_1."Id" AS "ProjectVersieId",
            pv_1."ProjectId",
            il."Id" AS "IndicatorLijstId",
            il."MeervoudsNaam" AS "IndicatorLijstMeervoudsNaam",
            il."EnkelFormulier" AS "IndicatorLijstEnkelFormulier",
            f."Id" AS "FormulierId",
            f."AanmaakDatum" AS "FormulierAanmaakDatum",
            i."Titel" AS "IndicatorTitel",
            a."Waarde"
           FROM (((((public."ProjectVersie" pv_1
             JOIN public."FormulierProjectVersie" fpv ON ((fpv."ProjectVersiesId" = pv_1."Id")))
             JOIN public."Formulier" f ON ((f."Id" = fpv."FormulierenId")))
             JOIN public."Antwoord" a ON ((a."FormulierId" = f."Id")))
             JOIN public."Indicator" i ON ((i."Id" = a."IndicatorId")))
             JOIN public."IndicatorLijst" il ON ((il."Id" = i."IndicatorLijstId")))
        ), projectversieattributenagg AS (
         SELECT projectversieattributen."ProjectVersieId",
            projectversieattributen."ProjectId",
            projectversieattributen."FormulierId",
            projectversieattributen."FormulierAanmaakDatum",
            projectversieattributen."IndicatorLijstId",
            projectversieattributen."IndicatorLijstMeervoudsNaam",
            projectversieattributen."IndicatorLijstEnkelFormulier",
            json_agg(json_build_object('IndicatorTitel', projectversieattributen."IndicatorTitel", 'Waarde', projectversieattributen."Waarde")) AS "FormulierWaardes"
           FROM projectversieattributen
          GROUP BY projectversieattributen."ProjectId", projectversieattributen."ProjectVersieId", projectversieattributen."FormulierId", projectversieattributen."FormulierAanmaakDatum", projectversieattributen."IndicatorLijstId", projectversieattributen."IndicatorLijstMeervoudsNaam", projectversieattributen."IndicatorLijstEnkelFormulier"
        ), projectversieindicatorlijstagg AS (
         SELECT projectversieattributenagg."ProjectVersieId",
            projectversieattributenagg."ProjectId",
            projectversieattributenagg."IndicatorLijstId",
            projectversieattributenagg."IndicatorLijstMeervoudsNaam",
            projectversieattributenagg."IndicatorLijstEnkelFormulier",
            json_agg(json_build_object('FormulierId', projectversieattributenagg."FormulierId", 'FormulierAanmaakDatum', projectversieattributenagg."FormulierAanmaakDatum", 'FormulierWaardes', projectversieattributenagg."FormulierWaardes")) AS "Formulier"
           FROM projectversieattributenagg
          GROUP BY projectversieattributenagg."ProjectVersieId", projectversieattributenagg."ProjectId", projectversieattributenagg."IndicatorLijstId", projectversieattributenagg."IndicatorLijstMeervoudsNaam", projectversieattributenagg."IndicatorLijstEnkelFormulier"
        ), projectversieagg AS (
         SELECT projectversieindicatorlijstagg."ProjectVersieId",
            projectversieindicatorlijstagg."ProjectId",
            json_agg(json_build_object('IndicatorLijstId', projectversieindicatorlijstagg."IndicatorLijstId", 'IndicatorLijstMeervoudsNaam', projectversieindicatorlijstagg."IndicatorLijstMeervoudsNaam", 'IndicatorLijstEnkelFormulier', projectversieindicatorlijstagg."IndicatorLijstEnkelFormulier", 'Formulier', projectversieindicatorlijstagg."Formulier")) AS "IndicatorLijstWaardes",
            array_agg(projectversieindicatorlijstagg."IndicatorLijstMeervoudsNaam") AS "IndicatorLijstBeschikbaar"
           FROM projectversieindicatorlijstagg
          GROUP BY projectversieindicatorlijstagg."ProjectVersieId", projectversieindicatorlijstagg."ProjectId"
        ), projectversiesamenvatting AS (
         SELECT projectversieattributen."ProjectVersieId",
            projectversieattributen."FormulierId",
            json_agg(json_build_object('IndicatorTitel', projectversieattributen."IndicatorTitel", 'Waarde', projectversieattributen."Waarde")) AS "ProjectSamenvatting"
           FROM projectversieattributen
          WHERE (((projectversieattributen."IndicatorLijstMeervoudsNaam" = 'Algemeen'::text) AND (projectversieattributen."IndicatorTitel" = 'Ministerie'::text)) OR ((projectversieattributen."IndicatorLijstMeervoudsNaam" = 'Algemeen'::text) AND (projectversieattributen."IndicatorTitel" = 'Projectstatus'::text)) OR ((projectversieattributen."IndicatorLijstMeervoudsNaam" = 'Algemeen'::text) AND (projectversieattributen."IndicatorTitel" = 'Projectstatus'::text)))
          GROUP BY projectversieattributen."ProjectVersieId", projectversieattributen."FormulierId"
        )
 SELECT p."Naam",
    p."LaatsteVersieId",
    pvs."ProjectSamenvatting" AS "Samenvatting",
    pv."Versie",
    pv."StatusId" AS "Status",
    pvagg."ProjectVersieId",
    pvagg."ProjectId",
    pvagg."IndicatorLijstWaardes",
    pvagg."IndicatorLijstBeschikbaar"
   FROM (((projectversieagg pvagg
     JOIN public."Project" p ON ((p."Id" = pvagg."ProjectId")))
     JOIN projectversiesamenvatting pvs ON ((pvs."ProjectVersieId" = pvagg."ProjectVersieId")))
     JOIN public."ProjectVersie" pv ON ((pv."Id" = pvagg."ProjectVersieId")))
  WHERE (pv."StatusId" = 3);


--
-- Name: vProjectIndicator; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public."vProjectIndicator" AS
 SELECT p."Naam",
    pv."Id" AS "ProjectVersieId",
    i."Id" AS "IndicatorId",
    il."Id" AS "IndicatorLijstId",
    pv."ProjectId",
    a."Id" AS "AntwoordId",
    f."Id" AS "FormulierId",
    pv."Versie" AS "ProjectVersie",
    pvst."Naam" AS "ProjectVersieStatusNaam",
    pvst."Id" AS "ProjectVersieStatusId",
    il."MeervoudsNaam" AS "IndicatorLijstMeervoudsNaam",
    il."EnkelFormulier" AS "IndicatorLijstEnkelFormulier",
    f."AanmaakDatum" AS "FormulierAanmaakDatum",
    i."Titel" AS "IndicatorTitel",
    a."Waarde",
    pv."WijzigingsDatum",
    m."Naam" AS "MinisterieNaam"
   FROM ((((((((public."ProjectVersie" pv
     JOIN public."FormulierProjectVersie" fpv ON ((fpv."ProjectVersiesId" = pv."Id")))
     JOIN public."Formulier" f ON ((f."Id" = fpv."FormulierenId")))
     JOIN public."Antwoord" a ON ((a."FormulierId" = f."Id")))
     JOIN public."Indicator" i ON ((i."Id" = a."IndicatorId")))
     JOIN public."IndicatorLijst" il ON ((il."Id" = i."IndicatorLijstId")))
     JOIN public."Project" p ON ((p."Id" = pv."ProjectId")))
     JOIN public."ProjectVersieStatus" pvst ON ((pvst."Id" = pv."StatusId")))
     JOIN public."Ministerie" m ON ((m."Id" = p."MinisterieId")));


--
-- Name: vUser; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public."vUser" AS
 WITH gebruikerministerieagg AS (
         SELECT gm_1."GebruikerId",
            array_to_string(array_agg(m."Naam"), ','::text) AS "Ministeries"
           FROM (public."GebruikerMinisterieNieuw" gm_1
             JOIN public."Ministerie" m ON ((m."Id" = gm_1."MinisterieId")))
          GROUP BY gm_1."GebruikerId"
        ), gebruikerorganisatieagg AS (
         SELECT go."GebruikerId",
            array_to_string(array_agg(o."Naam"), ','::text) AS "Organisaties"
           FROM (public."GebruikerOrganisatieNieuw" go
             JOIN public."Organisatie" o ON ((o."Id" = go."OrganisatieId")))
          GROUP BY go."GebruikerId"
        ), gebruikerrolagg AS (
         SELECT gr_1."GebruikerId",
            array_to_string(array_agg(r."Naam"), ','::text) AS "Rollen"
           FROM (public."GebruikerRol" gr_1
             JOIN public."Rol" r ON ((gr_1."RolId" = r."Id")))
          GROUP BY gr_1."GebruikerId"
        )
 SELECT g."Id",
    g."Naam",
    g."Actief",
    g."AanmaakDatum",
    g."WijzigingsDatum",
    g."KeycloakUserId",
    gm."Ministeries",
    g_o."Organisaties",
    gr."Rollen"
   FROM (((public."Gebruiker" g
     LEFT JOIN gebruikerministerieagg gm ON ((g."Id" = gm."GebruikerId")))
     LEFT JOIN gebruikerorganisatieagg g_o ON ((g."Id" = g_o."GebruikerId")))
     LEFT JOIN gebruikerrolagg gr ON ((g."Id" = gr."GebruikerId")));


--
-- Name: Aandachtspunt Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Aandachtspunt" ALTER COLUMN "Id" SET DEFAULT nextval('public."Aandachtspunt_Id_seq"'::regclass);


--
-- Name: Gebruiker Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gebruiker" ALTER COLUMN "Id" SET DEFAULT nextval('public."Gebruiker_Id_seq"'::regclass);


--
-- Name: GebruikerMinisterieNieuw Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterieNieuw" ALTER COLUMN "Id" SET DEFAULT nextval('public."GebruikerMinisterieNieuw_Id_seq"'::regclass);


--
-- Name: GebruikerOrganisatieNieuw Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatieNieuw" ALTER COLUMN "Id" SET DEFAULT nextval('public."GebruikerOrganisatieNieuw_Id_seq"'::regclass);


--
-- Name: GebruikerRol Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerRol" ALTER COLUMN "Id" SET DEFAULT nextval('public."GebruikerRol_Id_seq"'::regclass);


--
-- Name: Rol Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rol" ALTER COLUMN "Id" SET DEFAULT nextval('public."Rol_Id_seq"'::regclass);


--
-- Name: ToegangWijziging Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging" ALTER COLUMN "Id" SET DEFAULT nextval('public."ToegangWijziging_Id_seq"'::regclass);


--
-- Name: ministerie ministerie_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ministerie ALTER COLUMN ministerie_id SET DEFAULT nextval('public.ministerie_ministerie_id_seq'::regclass);


--
-- Name: project project_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project ALTER COLUMN project_id SET DEFAULT nextval('public.project_project_id_seq'::regclass);


--
-- Name: status status_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status ALTER COLUMN status_id SET DEFAULT nextval('public.status_status_id_seq'::regclass);


--
-- Name: Aandachtspunt Aandachtspunt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Aandachtspunt"
    ADD CONSTRAINT "Aandachtspunt_pkey" PRIMARY KEY ("Id");


--
-- Name: GebruikerMinisterieNieuw GebruikerMinisterieNieuw_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterieNieuw"
    ADD CONSTRAINT "GebruikerMinisterieNieuw_pkey" PRIMARY KEY ("Id");


--
-- Name: GebruikerOrganisatieNieuw GebruikerOrganisatieNieuw_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatieNieuw"
    ADD CONSTRAINT "GebruikerOrganisatieNieuw_pkey" PRIMARY KEY ("Id");


--
-- Name: GebruikerRol GebruikerRol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerRol"
    ADD CONSTRAINT "GebruikerRol_pkey" PRIMARY KEY ("Id");


--
-- Name: Gebruiker Gebruiker_Naam_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gebruiker"
    ADD CONSTRAINT "Gebruiker_Naam_key" UNIQUE ("Naam");


--
-- Name: Gebruiker Gebruiker_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gebruiker"
    ADD CONSTRAINT "Gebruiker_pkey" PRIMARY KEY ("Id");


--
-- Name: Antwoord PK_Antwoord; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Antwoord"
    ADD CONSTRAINT "PK_Antwoord" PRIMARY KEY ("Id");


--
-- Name: AntwoordOptie PK_AntwoordOptie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AntwoordOptie"
    ADD CONSTRAINT "PK_AntwoordOptie" PRIMARY KEY ("Id");


--
-- Name: AntwoordType PK_AntwoordType; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AntwoordType"
    ADD CONSTRAINT "PK_AntwoordType" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Formulier PK_Formulier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Formulier"
    ADD CONSTRAINT "PK_Formulier" PRIMARY KEY ("Id");


--
-- Name: FormulierProjectVersie PK_FormulierProjectVersie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FormulierProjectVersie"
    ADD CONSTRAINT "PK_FormulierProjectVersie" PRIMARY KEY ("FormulierenId", "ProjectVersiesId");


--
-- Name: GebruikerMinisterie PK_GebruikerMinisterie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterie"
    ADD CONSTRAINT "PK_GebruikerMinisterie" PRIMARY KEY ("GebruikersId", "MinisteriesId");


--
-- Name: GebruikerOrganisatie PK_GebruikerOrganisatie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatie"
    ADD CONSTRAINT "PK_GebruikerOrganisatie" PRIMARY KEY ("GebruikersId", "OrganisatiesId");


--
-- Name: GebruikerProject PK_GebruikerProject; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerProject"
    ADD CONSTRAINT "PK_GebruikerProject" PRIMARY KEY ("GebruikersId", "ProjectenId");


--
-- Name: Indicator PK_Indicator; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Indicator"
    ADD CONSTRAINT "PK_Indicator" PRIMARY KEY ("Id");


--
-- Name: IndicatorLijst PK_IndicatorLijst; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."IndicatorLijst"
    ADD CONSTRAINT "PK_IndicatorLijst" PRIMARY KEY ("Id");


--
-- Name: Ministerie PK_Ministerie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ministerie"
    ADD CONSTRAINT "PK_Ministerie" PRIMARY KEY ("Id");


--
-- Name: Organisatie PK_Organisatie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Organisatie"
    ADD CONSTRAINT "PK_Organisatie" PRIMARY KEY ("Id");


--
-- Name: Project PK_Project; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT "PK_Project" PRIMARY KEY ("Id");


--
-- Name: ProjectVersie PK_ProjectVersie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersie"
    ADD CONSTRAINT "PK_ProjectVersie" PRIMARY KEY ("Id");


--
-- Name: ProjectVersiePreviewToken PK_ProjectVersiePreviewToken; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersiePreviewToken"
    ADD CONSTRAINT "PK_ProjectVersiePreviewToken" PRIMARY KEY ("Id");


--
-- Name: ProjectVersieStatus PK_ProjectVersieStatus; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersieStatus"
    ADD CONSTRAINT "PK_ProjectVersieStatus" PRIMARY KEY ("Id");


--
-- Name: StatusChange PK_StatusChange; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StatusChange"
    ADD CONSTRAINT "PK_StatusChange" PRIMARY KEY ("Id");


--
-- Name: Tabeleigenschap PK_Tabeleigenschap; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tabeleigenschap"
    ADD CONSTRAINT "PK_Tabeleigenschap" PRIMARY KEY ("Id");


--
-- Name: TabeleigenschapIndicator PK_TabeleigenschapIndicator; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TabeleigenschapIndicator"
    ADD CONSTRAINT "PK_TabeleigenschapIndicator" PRIMARY KEY ("Id");


--
-- Name: TabeleigenschapType PK_TabeleigenschapType; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TabeleigenschapType"
    ADD CONSTRAINT "PK_TabeleigenschapType" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: Project Project_LegacyProjectId_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT "Project_LegacyProjectId_key" UNIQUE ("LegacyProjectId");


--
-- Name: Rol Rol_Naam_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rol"
    ADD CONSTRAINT "Rol_Naam_key" UNIQUE ("Naam");


--
-- Name: Rol Rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rol"
    ADD CONSTRAINT "Rol_pkey" PRIMARY KEY ("Id");


--
-- Name: ToegangWijziging ToegangWijziging_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging"
    ADD CONSTRAINT "ToegangWijziging_pkey" PRIMARY KEY ("Id");


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: ministerie ministerie_afkorting_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ministerie
    ADD CONSTRAINT ministerie_afkorting_key UNIQUE (afkorting);


--
-- Name: ministerie ministerie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ministerie
    ADD CONSTRAINT ministerie_pkey PRIMARY KEY (ministerie_id);


--
-- Name: project project_naam_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_naam_key UNIQUE (naam);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (project_id);


--
-- Name: status status_omschrijving_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_omschrijving_key UNIQUE (omschrijving);


--
-- Name: status status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (status_id);


--
-- Name: GebruikerMinisterieNieuw uq_gebruiker_ministerie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterieNieuw"
    ADD CONSTRAINT uq_gebruiker_ministerie UNIQUE ("GebruikerId", "MinisterieId");


--
-- Name: GebruikerOrganisatieNieuw uq_gebruiker_organisatie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatieNieuw"
    ADD CONSTRAINT uq_gebruiker_organisatie UNIQUE ("GebruikerId", "OrganisatieId");


--
-- Name: GebruikerRol uq_gebruiker_rol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerRol"
    ADD CONSTRAINT uq_gebruiker_rol UNIQUE ("GebruikerId", "RolId");


--
-- Name: Organisatie uq_organisatie; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Organisatie"
    ADD CONSTRAINT uq_organisatie UNIQUE ("Naam");


--
-- Name: Project uq_project_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT uq_project_slug UNIQUE ("Slug");


--
-- Name: ProjectVersie uq_project_versie_versienummer; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersie"
    ADD CONSTRAINT uq_project_versie_versienummer UNIQUE ("ProjectId", "Versie");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AntwoordOptie_IndicatorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AntwoordOptie_IndicatorId" ON public."AntwoordOptie" USING btree ("IndicatorId");


--
-- Name: IX_Antwoord_FormulierId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Antwoord_FormulierId" ON public."Antwoord" USING btree ("FormulierId");


--
-- Name: IX_Antwoord_IndicatorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Antwoord_IndicatorId" ON public."Antwoord" USING btree ("IndicatorId");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_FormulierProjectVersie_ProjectVersiesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_FormulierProjectVersie_ProjectVersiesId" ON public."FormulierProjectVersie" USING btree ("ProjectVersiesId");


--
-- Name: IX_Formulier_GebruikerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Formulier_GebruikerId" ON public."Formulier" USING btree ("GebruikerId");


--
-- Name: IX_Formulier_IndicatorLijstId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Formulier_IndicatorLijstId" ON public."Formulier" USING btree ("IndicatorLijstId");


--
-- Name: IX_GebruikerMinisterie_MinisteriesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GebruikerMinisterie_MinisteriesId" ON public."GebruikerMinisterie" USING btree ("MinisteriesId");


--
-- Name: IX_GebruikerOrganisatie_OrganisatiesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GebruikerOrganisatie_OrganisatiesId" ON public."GebruikerOrganisatie" USING btree ("OrganisatiesId");


--
-- Name: IX_GebruikerProject_ProjectenId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GebruikerProject_ProjectenId" ON public."GebruikerProject" USING btree ("ProjectenId");


--
-- Name: IX_Indicator_AntwoordTypeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Indicator_AntwoordTypeId" ON public."Indicator" USING btree ("AntwoordTypeId");


--
-- Name: IX_Indicator_IndicatorLijstId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Indicator_IndicatorLijstId" ON public."Indicator" USING btree ("IndicatorLijstId");


--
-- Name: IX_Organisatie_MinisterieId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Organisatie_MinisterieId" ON public."Organisatie" USING btree ("MinisterieId");


--
-- Name: IX_ProjectVersiePreviewToken_ProjectVersieId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ProjectVersiePreviewToken_ProjectVersieId" ON public."ProjectVersiePreviewToken" USING btree ("ProjectVersieId");


--
-- Name: IX_ProjectVersie_ProjectId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ProjectVersie_ProjectId" ON public."ProjectVersie" USING btree ("ProjectId");


--
-- Name: IX_ProjectVersie_ProjectVersieStatusId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ProjectVersie_ProjectVersieStatusId" ON public."ProjectVersie" USING btree ("ProjectVersieStatusId");


--
-- Name: IX_Project_MinisterieId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Project_MinisterieId" ON public."Project" USING btree ("MinisterieId");


--
-- Name: IX_Project_OrganisatieId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Project_OrganisatieId" ON public."Project" USING btree ("OrganisatieId");


--
-- Name: IX_StatusChange_ProjectVersieId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_StatusChange_ProjectVersieId" ON public."StatusChange" USING btree ("ProjectVersieId");


--
-- Name: IX_TabeleigenschapIndicator_IndicatorId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_TabeleigenschapIndicator_IndicatorId" ON public."TabeleigenschapIndicator" USING btree ("IndicatorId");


--
-- Name: IX_TabeleigenschapIndicator_KolomId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_TabeleigenschapIndicator_KolomId" ON public."TabeleigenschapIndicator" USING btree ("KolomId");


--
-- Name: IX_TabeleigenschapIndicator_RijId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_TabeleigenschapIndicator_RijId" ON public."TabeleigenschapIndicator" USING btree ("RijId");


--
-- Name: IX_Tabeleigenschap_TabelIndicatorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tabeleigenschap_TabelIndicatorId" ON public."Tabeleigenschap" USING btree ("TabelIndicatorId");


--
-- Name: IX_Tabeleigenschap_TypeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Tabeleigenschap_TypeId" ON public."Tabeleigenschap" USING btree ("TypeId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: Aandachtspunt Aandachtspunt_GewijzigdDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Aandachtspunt"
    ADD CONSTRAINT "Aandachtspunt_GewijzigdDoorGebruikerId_fkey" FOREIGN KEY ("GewijzigdDoorGebruikerId") REFERENCES public."Gebruiker"("Id");


--
-- Name: Antwoord Antwoord_AangemaaktDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Antwoord"
    ADD CONSTRAINT "Antwoord_AangemaaktDoorGebruikerId_fkey" FOREIGN KEY ("AangemaaktDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: Antwoord Antwoord_GewijzigdDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Antwoord"
    ADD CONSTRAINT "Antwoord_GewijzigdDoorGebruikerId_fkey" FOREIGN KEY ("GewijzigdDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: AntwoordOptie FK_AntwoordOptie_Indicator_IndicatorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AntwoordOptie"
    ADD CONSTRAINT "FK_AntwoordOptie_Indicator_IndicatorId" FOREIGN KEY ("IndicatorId") REFERENCES public."Indicator"("Id") ON DELETE CASCADE;


--
-- Name: Antwoord FK_Antwoord_Formulier_FormulierId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Antwoord"
    ADD CONSTRAINT "FK_Antwoord_Formulier_FormulierId" FOREIGN KEY ("FormulierId") REFERENCES public."Formulier"("Id") ON DELETE CASCADE;


--
-- Name: Antwoord FK_Antwoord_Indicator_IndicatorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Antwoord"
    ADD CONSTRAINT "FK_Antwoord_Indicator_IndicatorId" FOREIGN KEY ("IndicatorId") REFERENCES public."Indicator"("Id") ON DELETE CASCADE;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: FormulierProjectVersie FK_FormulierProjectVersie_Formulier_FormulierenId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FormulierProjectVersie"
    ADD CONSTRAINT "FK_FormulierProjectVersie_Formulier_FormulierenId" FOREIGN KEY ("FormulierenId") REFERENCES public."Formulier"("Id") ON DELETE CASCADE;


--
-- Name: FormulierProjectVersie FK_FormulierProjectVersie_ProjectVersie_ProjectVersiesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FormulierProjectVersie"
    ADD CONSTRAINT "FK_FormulierProjectVersie_ProjectVersie_ProjectVersiesId" FOREIGN KEY ("ProjectVersiesId") REFERENCES public."ProjectVersie"("Id") ON DELETE CASCADE;


--
-- Name: Formulier FK_Formulier_AspNetUsers_GebruikerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Formulier"
    ADD CONSTRAINT "FK_Formulier_AspNetUsers_GebruikerId" FOREIGN KEY ("GebruikerId") REFERENCES public."AspNetUsers"("Id");


--
-- Name: Formulier FK_Formulier_IndicatorLijst_IndicatorLijstId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Formulier"
    ADD CONSTRAINT "FK_Formulier_IndicatorLijst_IndicatorLijstId" FOREIGN KEY ("IndicatorLijstId") REFERENCES public."IndicatorLijst"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerMinisterie FK_GebruikerMinisterie_AspNetUsers_GebruikersId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterie"
    ADD CONSTRAINT "FK_GebruikerMinisterie_AspNetUsers_GebruikersId" FOREIGN KEY ("GebruikersId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerMinisterie FK_GebruikerMinisterie_Ministerie_MinisteriesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterie"
    ADD CONSTRAINT "FK_GebruikerMinisterie_Ministerie_MinisteriesId" FOREIGN KEY ("MinisteriesId") REFERENCES public."Ministerie"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerOrganisatie FK_GebruikerOrganisatie_AspNetUsers_GebruikersId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatie"
    ADD CONSTRAINT "FK_GebruikerOrganisatie_AspNetUsers_GebruikersId" FOREIGN KEY ("GebruikersId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerOrganisatie FK_GebruikerOrganisatie_Organisatie_OrganisatiesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatie"
    ADD CONSTRAINT "FK_GebruikerOrganisatie_Organisatie_OrganisatiesId" FOREIGN KEY ("OrganisatiesId") REFERENCES public."Organisatie"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerProject FK_GebruikerProject_AspNetUsers_GebruikersId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerProject"
    ADD CONSTRAINT "FK_GebruikerProject_AspNetUsers_GebruikersId" FOREIGN KEY ("GebruikersId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerProject FK_GebruikerProject_Project_ProjectenId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerProject"
    ADD CONSTRAINT "FK_GebruikerProject_Project_ProjectenId" FOREIGN KEY ("ProjectenId") REFERENCES public."Project"("Id") ON DELETE CASCADE;


--
-- Name: Indicator FK_Indicator_AntwoordType_AntwoordTypeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Indicator"
    ADD CONSTRAINT "FK_Indicator_AntwoordType_AntwoordTypeId" FOREIGN KEY ("AntwoordTypeId") REFERENCES public."AntwoordType"("Id") ON DELETE CASCADE;


--
-- Name: Indicator FK_Indicator_IndicatorLijst_IndicatorLijstId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Indicator"
    ADD CONSTRAINT "FK_Indicator_IndicatorLijst_IndicatorLijstId" FOREIGN KEY ("IndicatorLijstId") REFERENCES public."IndicatorLijst"("Id") ON DELETE CASCADE;


--
-- Name: Organisatie FK_Organisatie_Ministerie_MinisterieId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Organisatie"
    ADD CONSTRAINT "FK_Organisatie_Ministerie_MinisterieId" FOREIGN KEY ("MinisterieId") REFERENCES public."Ministerie"("Id") ON DELETE CASCADE;


--
-- Name: ProjectVersiePreviewToken FK_ProjectVersiePreviewToken_ProjectVersie_ProjectVersieId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersiePreviewToken"
    ADD CONSTRAINT "FK_ProjectVersiePreviewToken_ProjectVersie_ProjectVersieId" FOREIGN KEY ("ProjectVersieId") REFERENCES public."ProjectVersie"("Id") ON DELETE CASCADE;


--
-- Name: ProjectVersie FK_ProjectVersie_ProjectVersieStatus_ProjectVersieStatusId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersie"
    ADD CONSTRAINT "FK_ProjectVersie_ProjectVersieStatus_ProjectVersieStatusId" FOREIGN KEY ("ProjectVersieStatusId") REFERENCES public."ProjectVersieStatus"("Id");


--
-- Name: ProjectVersie FK_ProjectVersie_Project_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersie"
    ADD CONSTRAINT "FK_ProjectVersie_Project_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public."Project"("Id") ON DELETE CASCADE;


--
-- Name: Project FK_Project_Ministerie_MinisterieId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT "FK_Project_Ministerie_MinisterieId" FOREIGN KEY ("MinisterieId") REFERENCES public."Ministerie"("Id");


--
-- Name: Project FK_Project_Organisatie_OrganisatieId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Project"
    ADD CONSTRAINT "FK_Project_Organisatie_OrganisatieId" FOREIGN KEY ("OrganisatieId") REFERENCES public."Organisatie"("Id");


--
-- Name: StatusChange FK_StatusChange_ProjectVersie_ProjectVersieId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StatusChange"
    ADD CONSTRAINT "FK_StatusChange_ProjectVersie_ProjectVersieId" FOREIGN KEY ("ProjectVersieId") REFERENCES public."ProjectVersie"("Id") ON DELETE CASCADE;


--
-- Name: TabeleigenschapIndicator FK_TabeleigenschapIndicator_Indicator_IndicatorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TabeleigenschapIndicator"
    ADD CONSTRAINT "FK_TabeleigenschapIndicator_Indicator_IndicatorId" FOREIGN KEY ("IndicatorId") REFERENCES public."Indicator"("Id") ON DELETE CASCADE;


--
-- Name: TabeleigenschapIndicator FK_TabeleigenschapIndicator_Tabeleigenschap_KolomId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TabeleigenschapIndicator"
    ADD CONSTRAINT "FK_TabeleigenschapIndicator_Tabeleigenschap_KolomId" FOREIGN KEY ("KolomId") REFERENCES public."Tabeleigenschap"("Id");


--
-- Name: TabeleigenschapIndicator FK_TabeleigenschapIndicator_Tabeleigenschap_RijId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TabeleigenschapIndicator"
    ADD CONSTRAINT "FK_TabeleigenschapIndicator_Tabeleigenschap_RijId" FOREIGN KEY ("RijId") REFERENCES public."Tabeleigenschap"("Id");


--
-- Name: Tabeleigenschap FK_Tabeleigenschap_Indicator_TabelIndicatorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tabeleigenschap"
    ADD CONSTRAINT "FK_Tabeleigenschap_Indicator_TabelIndicatorId" FOREIGN KEY ("TabelIndicatorId") REFERENCES public."Indicator"("Id") ON DELETE CASCADE;


--
-- Name: Tabeleigenschap FK_Tabeleigenschap_TabeleigenschapType_TypeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tabeleigenschap"
    ADD CONSTRAINT "FK_Tabeleigenschap_TabeleigenschapType_TypeId" FOREIGN KEY ("TypeId") REFERENCES public."TabeleigenschapType"("Id") ON DELETE CASCADE;


--
-- Name: Formulier Formulier_AangemaaktDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Formulier"
    ADD CONSTRAINT "Formulier_AangemaaktDoorGebruikerId_fkey" FOREIGN KEY ("AangemaaktDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: Formulier Formulier_GewijzigdDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Formulier"
    ADD CONSTRAINT "Formulier_GewijzigdDoorGebruikerId_fkey" FOREIGN KEY ("GewijzigdDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: GebruikerMinisterieNieuw GebruikerMinisterieNieuw_GebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterieNieuw"
    ADD CONSTRAINT "GebruikerMinisterieNieuw_GebruikerId_fkey" FOREIGN KEY ("GebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerMinisterieNieuw GebruikerMinisterieNieuw_MinisterieId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerMinisterieNieuw"
    ADD CONSTRAINT "GebruikerMinisterieNieuw_MinisterieId_fkey" FOREIGN KEY ("MinisterieId") REFERENCES public."Ministerie"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerOrganisatieNieuw GebruikerOrganisatieNieuw_GebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatieNieuw"
    ADD CONSTRAINT "GebruikerOrganisatieNieuw_GebruikerId_fkey" FOREIGN KEY ("GebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerOrganisatieNieuw GebruikerOrganisatieNieuw_OrganisatieId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerOrganisatieNieuw"
    ADD CONSTRAINT "GebruikerOrganisatieNieuw_OrganisatieId_fkey" FOREIGN KEY ("OrganisatieId") REFERENCES public."Organisatie"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerRol GebruikerRol_GebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerRol"
    ADD CONSTRAINT "GebruikerRol_GebruikerId_fkey" FOREIGN KEY ("GebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE CASCADE;


--
-- Name: GebruikerRol GebruikerRol_RolId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GebruikerRol"
    ADD CONSTRAINT "GebruikerRol_RolId_fkey" FOREIGN KEY ("RolId") REFERENCES public."Rol"("Id") ON DELETE CASCADE;


--
-- Name: ProjectVersie ProjectVersie_AangemaaktDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersie"
    ADD CONSTRAINT "ProjectVersie_AangemaaktDoorGebruikerId_fkey" FOREIGN KEY ("AangemaaktDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: ProjectVersie ProjectVersie_GewijzigdDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProjectVersie"
    ADD CONSTRAINT "ProjectVersie_GewijzigdDoorGebruikerId_fkey" FOREIGN KEY ("GewijzigdDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: StatusChange StatusChange_GebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StatusChange"
    ADD CONSTRAINT "StatusChange_GebruikerId_fkey" FOREIGN KEY ("GebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: ToegangWijziging ToegangWijziging_GewijzigdDoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging"
    ADD CONSTRAINT "ToegangWijziging_GewijzigdDoorGebruikerId_fkey" FOREIGN KEY ("GewijzigdDoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE SET NULL;


--
-- Name: ToegangWijziging ToegangWijziging_GewijzigdVoorGebruikerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging"
    ADD CONSTRAINT "ToegangWijziging_GewijzigdVoorGebruikerId_fkey" FOREIGN KEY ("GewijzigdVoorGebruikerId") REFERENCES public."Gebruiker"("Id") ON DELETE CASCADE;


--
-- Name: ToegangWijziging ToegangWijziging_MinisterieId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging"
    ADD CONSTRAINT "ToegangWijziging_MinisterieId_fkey" FOREIGN KEY ("MinisterieId") REFERENCES public."Ministerie"("Id") ON DELETE CASCADE;


--
-- Name: ToegangWijziging ToegangWijziging_OrganisatieId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging"
    ADD CONSTRAINT "ToegangWijziging_OrganisatieId_fkey" FOREIGN KEY ("OrganisatieId") REFERENCES public."Organisatie"("Id") ON DELETE CASCADE;


--
-- Name: ToegangWijziging ToegangWijziging_RolId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToegangWijziging"
    ADD CONSTRAINT "ToegangWijziging_RolId_fkey" FOREIGN KEY ("RolId") REFERENCES public."Rol"("Id") ON DELETE CASCADE;


--
-- Name: StatusChange fk_status_change_project_versie; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StatusChange"
    ADD CONSTRAINT fk_status_change_project_versie FOREIGN KEY ("ProjectVersieId") REFERENCES public."ProjectVersie"("Id");


--
-- Name: StatusChange fk_status_change_project_versie_status; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StatusChange"
    ADD CONSTRAINT fk_status_change_project_versie_status FOREIGN KEY ("Status") REFERENCES public."ProjectVersieStatus"("Id");


--
-- Name: project project_ministerie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_ministerie_id_fkey FOREIGN KEY (ministerie_id) REFERENCES public.ministerie(ministerie_id);


--
-- Name: project project_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.status(status_id);


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.9
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: rid-data
--

COPY public.alembic_version (version_num) FROM stdin;
922d550cf2d1
\.


--
-- PostgreSQL database dump complete
--

